// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agent status in the platform
 */
export type AgentStatus = "active" | "inactive" | "maintenance" | "training";
