// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatus } from "./AgentStatus";

/**
 * Query params for agent search/filter
 */
export type AgentSearchQuery = { 
/**
 * Search term for name, designation, or description
 */
q: string | null, 
/**
 * Filter by status
 */
status: AgentStatus | null, 
/**
 * Filter by capability
 */
capability: string | null, 
/**
 * Sort by field
 */
sort_by: string | null, 
/**
 * Sort direction (asc/desc)
 */
sort_dir: string | null, };
