// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClosedUnpaidProject = { id: string, name: string, client_name: string | null, updated_at: string, };
