// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClosedUnpaidProject } from "./ClosedUnpaidProject";
import type { DueSoonDeliverable } from "./DueSoonDeliverable";
import type { FollowUpLead } from "./FollowUpLead";
import type { OverdueTask } from "./OverdueTask";
import type { PendingProposal } from "./PendingProposal";
import type { WaitingProject } from "./WaitingProject";

export type CommandCenterSnapshot = { overdue_tasks: Array<OverdueTask>, deliverables_due_this_week: Array<DueSoonDeliverable>, waiting_on_client_projects: Array<WaitingProject>, follow_up_required: Array<FollowUpLead>, proposals_awaiting_approval: Array<PendingProposal>, closed_unpaid_projects: Array<ClosedUnpaidProject>, };
