// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Complete an org segment
 */
export type CompleteOrgSegmentRequest = { user_decisions: string | null, skip: boolean, };
