// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Complete a segment
 */
export type CompleteSegmentRequest = { user_decisions: string | null, skip: boolean, };
