// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConvertEntityRequest = { source_type: string, source_id: string, target_type: string, target_parent_id: string | null, };
