// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query params for cost estimation
 */
export type CostEstimateQuery = { model: string, input_tokens: bigint, output_tokens: bigint, provider: string | null, };
