// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateOssLibrary = { name: string, github_owner: string, github_repo: string, notes: string | null, check_interval_secs: bigint | null, };
