// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrchestrationTaskType } from "./OrchestrationTaskType";

export type CreateTaskRequest = { task_type: OrchestrationTaskType, description: string, is_concurrency_safe: boolean, tool_use_id: string | null, };
