// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessInfo } from "./ProcessInfo";
import type { SystemMetrics } from "./SystemMetrics";

export type DetailedSystemMetrics = { metrics: SystemMetrics, top_processes: Array<ProcessInfo>, per_cpu_usage: Array<number>, };
