// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DueSoonDeliverable = { id: string, title: string, deliverable_type: string, project_name: string, status: string, due_date: string, };
