// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FollowUpLead = { id: string, full_name: string, email: string | null, follow_up_attempts: bigint, lifecycle_stage: string, };
