// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Request body Jungleverse (or any consumer) sends to the gateway
 */
export type GatewayServiceRequest = { 
/**
 * Service type to route to: 'compute', 'web-hosting', 'data-api', 'proxy', etc.
 */
service_type: string, 
/**
 * Optional: pin to a specific listing (provider) by ID
 */
listing_id: string | null, 
/**
 * The actual payload to forward to the provider (service-specific JSON)
 */
payload: JsonValue, 
/**
 * Caller's HTTP method (for proxy services)
 */
method: string | null, 
/**
 * Caller's path (for proxy/hosting services)
 */
path: string | null, };
