// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type GatewayServiceResponse = { request_id: string, provider_node_id: string, status: string, response: JsonValue, vibe_charged: number, response_ms: bigint, };
