// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetworkStatsResponse = { total_peers: bigint, active_peers: bigint, total_rewards_distributed: number, total_pending_rewards: number, total_batches: bigint, };
