// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of the overall onboarding process
 */
export type OnboardingStatus = "active" | "paused" | "completed" | "cancelled";
