// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OnboardingSegment } from "./OnboardingSegment";
import type { ProjectOnboarding } from "./ProjectOnboarding";

/**
 * Response for onboarding with segments
 */
export type OnboardingWithSegments = { onboarding: ProjectOnboarding, segments: Array<OnboardingSegment>, };
