// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SegmentStatus } from "./SegmentStatus";
import type { SegmentType } from "./SegmentType";

/**
 * Individual onboarding segment (carousel item)
 */
export type OnboardingSegment = { id: string, project_id: string, onboarding_id: string, segment_type: SegmentType, name: string, assigned_agent_id?: string | null, assigned_agent_name?: string | null, status: SegmentStatus, recommendations?: string | null, user_decisions?: string | null, order_index: number, started_at?: string | null, completed_at?: string | null, created_at: string, updated_at: string, };
