// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrchestrationTaskType } from "./OrchestrationTaskType";

/**
 * Events emitted during orchestration task execution
 */
export type OrchestrationEvent = { "type": "task_queued", task_id: string, task_type: OrchestrationTaskType, description: string, position: number, } | { "type": "task_started", task_id: string, task_type: OrchestrationTaskType, } | { "type": "task_progress", task_id: string, 
/**
 * Human-readable progress message
 */
progress: string, 
/**
 * Optional percentage (0-100)
 */
percent: number | null, } | { "type": "task_completed", task_id: string, 
/**
 * Task output/result
 */
output: string, 
/**
 * Duration in milliseconds
 */
duration_ms: bigint, } | { "type": "task_failed", task_id: string, 
/**
 * Error message
 */
error: string, 
/**
 * Duration in milliseconds
 */
duration_ms: bigint | null, } | { "type": "task_killed", task_id: string, 
/**
 * Duration in milliseconds before kill
 */
duration_ms: bigint | null, } | { "type": "flow_completed", flow_id: string, 
/**
 * Total duration in milliseconds
 */
total_duration_ms: bigint, 
/**
 * Number of tasks that completed successfully
 */
completed_count: number, 
/**
 * Number of tasks that failed
 */
failed_count: number, } | { "type": "flow_error", flow_id: string, error: string, };
