// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrchestrationTask } from "./OrchestrationTask";

export type OrchestrationTasksResponse = { tasks: Array<OrchestrationTask>, pending_count: number, running_count: number, completed_count: number, failed_count: number, };
