// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The execution status of an orchestration task.
 */
export type OrchestrationTaskStatus = "pending" | "running" | "completed" | "failed" | "killed";
