// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrgOnboarding } from "./OrgOnboarding";
import type { OrgOnboardingSegment } from "./OrgOnboardingSegment";

/**
 * Response for org onboarding with segments
 */
export type OrgOnboardingWithSegments = { onboarding: OrgOnboarding, segments: Array<OrgOnboardingSegment>, };
