// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OverdueTask = { id: string, title: string, project_name: string, due_date: string, assignee_name: string | null, };
