// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatchOssLibrary = { name: string | null, notes: string | null, check_interval_secs: bigint | null, is_active: boolean | null, };
