// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatchRouterModel = { name: string | null, priority: bigint | null, is_enabled: boolean | null, provider_base_url: string | null, api_key_env_var: string | null, api_key_value: string | null, };
