// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeerStatsResponse = { node_id: string, wallet_address: string, cpu_cores: bigint | null, ram_mb: bigint | null, storage_gb: bigint | null, gpu_available: boolean, gpu_model: string | null, last_heartbeat_at: string | null, is_active: boolean, total_earned: number, };
