// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PendingProposal = { id: string, title: string, lead_name: string | null, quote_amount_vibe: bigint, created_at: string, };
