// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProcessInfo = { name: string, pid: number, cpu_usage: number, memory_bytes: bigint, };
