// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectVibeBalance = { project_id: string, total_deposited: bigint, total_withdrawn: bigint, total_spent: bigint, available_balance: bigint, };
