// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OnboardingStatus } from "./OnboardingStatus";

/**
 * Main project onboarding record
 */
export type ProjectOnboarding = { id: string, project_id: string, status: OnboardingStatus, current_phase: string, context_data?: string | null, recommendations?: string | null, started_at: string, completed_at?: string | null, created_at: string, updated_at: string, };
