// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectKnowledgeCompleteness } from "./ProjectKnowledgeCompleteness";
import type { ProjectKnowledgeSource } from "./ProjectKnowledgeSource";

/**
 * Grouped knowledge sources response
 */
export type ProjectKnowledgeResponse = { project_id: string, completeness: ProjectKnowledgeCompleteness | null, total_sources: number, stale_count: number, sources_by_type: { [key in string]?: Array<ProjectKnowledgeSource> }, };
