// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectAccessResponse = { has_access: boolean, role: string | null, can_read: boolean, can_write: boolean, can_manage_members: boolean, can_delete: boolean, };
