// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectMemberItem = { id: string, project_id: string, user_id: string, username: string, full_name: string, email: string, avatar_url: string | null, role: string, granted_at: string, granted_by_username: string | null, };
