// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PulseContentItem } from "./PulseContentItem";

export type PulseContentResponse = { items: Array<PulseContentItem>, count: number, };
