// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PulseProject = { name: string, description: string | null, adapters: bigint, active_sources: Array<string>, scheduler_running: boolean, };
