// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PulseDashboardStats = { total_content: bigint, total_sources: number, active_sources: number, unacknowledged_alerts: bigint, };
