// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PulseProject } from "./PulseProject";

export type PulseProjectsResponse = { projects: Array<PulseProject>, count: number, };
