// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowStatus } from "./FlowStatus";

export type RespondClarificationPayload = { response: string, 
/**
 * Resume to this status after clarification (default: previous status before NeedsClarification)
 */
resume_status: FlowStatus | null, };
