// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Types of onboarding segments
 */
export type SegmentType = "research" | "brand" | "website" | "email" | "legal" | "social" | "custom";
