// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of individual onboarding segments
 */
export type SegmentStatus = "pending" | "in_progress" | "needs_review" | "completed" | "skipped";
