// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SidebarSharedBoard } from "./SidebarSharedBoard";

export type SidebarSharedBoardGroup = { source_org_id: string, source_org_name: string, share_type: string, boards: Array<SidebarSharedBoard>, };
