// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SidebarClient } from "./SidebarClient";
import type { SidebarProject } from "./SidebarProject";
import type { SidebarSharedBoardGroup } from "./SidebarSharedBoardGroup";

export type SidebarOrg = { id: string, name: string, slug: string, role: string, health_status: string | null, active_issues_count: bigint | null, knowledge_completeness: number | null, last_activity_at: string | null, internal_projects: Array<SidebarProject>, clients: Array<SidebarClient>, shared_boards: Array<SidebarSharedBoardGroup>, };
