// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SidebarSharedBoard = { board_id: string, board_name: string, project_id: string, project_name: string, permission: string, share_type: string, };
