// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StageValidation = { "type": "require_field", field: string, message: string, } | { "type": "require_intel", entity: string, status: string, } | { "type": "require_pending_tasks", count: number, } | { "type": "require_transcript_or_source", message: string, };
