// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StageAction = { "type": "trigger_agent", agent: string, flow_type: string, } | { "type": "create_review_task", description: string, } | { "type": "create_delivery_deal" };
