// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StageAction } from "./StageAction";
import type { StageOwner } from "./StageOwner";
import type { StageValidation } from "./StageValidation";

export type StageConfig = { assigned_agent: string | null, auto_trigger: boolean, cancel_window_secs: number, required_fields: Array<string>, approval_gate: boolean, on_enter_actions: Array<StageAction>, on_exit_validations: Array<StageValidation>, stage_owner: StageOwner | null, 
/**
 * User ID or username to assign review tasks to. Falls back to org owner if not set.
 */
review_assignee: string | null, 
/**
 * If true, deals entering this stage immediately auto-advance to the next stage.
 * Useful for optional stages (e.g., Lead) that some pipelines want to skip.
 */
auto_skip: boolean, };
