// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmitFeedbackRequest = { 
/**
 * Type of feedback: bug, feature, improvement, question, friction, other
 */
feedback_type: string, 
/**
 * Brief title/summary (max 200 chars)
 */
title: string, 
/**
 * Detailed description (max 5000 chars)
 */
description: string, 
/**
 * Reporter's email (optional)
 */
email: string | null, 
/**
 * Severity for bugs: low, medium, high, critical
 */
severity: string | null, 
/**
 * Base64 encoded screenshot image (optional)
 */
screenshot: string | null, 
/**
 * Page/route where friction occurred (e.g. "/crm/deals")
 */
page_url?: string, 
/**
 * What the user was trying to do (max 1000 chars)
 */
user_intent?: string, 
/**
 * What went wrong or felt slow/confusing (max 1000 chars)
 */
friction_point?: string, 
/**
 * Expected behavior vs actual (max 1000 chars)
 */
expected_behavior?: string, 
/**
 * Time spent blocked (seconds, self-reported)
 */
time_lost_seconds?: number, 
/**
 * Frustration level: 1 (minor) to 5 (show-stopper)
 */
frustration_level?: number, };
