// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmitFeedbackRequest = { 
/**
 * Type of feedback: bug, feature, improvement, question, other
 */
feedback_type: string, 
/**
 * Brief title/summary
 */
title: string, 
/**
 * Detailed description
 */
description: string, 
/**
 * Reporter's email (optional)
 */
email: string | null, 
/**
 * Severity for bugs: low, medium, high, critical
 */
severity: string | null, 
/**
 * Base64 encoded screenshot image (optional)
 */
screenshot: string | null, };
