// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadAverage } from "./LoadAverage";

export type SystemMetrics = { cpu_usage_percent: number, memory_used_bytes: bigint, memory_total_bytes: bigint, memory_usage_percent: number, disk_used_bytes: bigint, disk_total_bytes: bigint, disk_usage_percent: number, process_count: number, uptime_seconds: bigint, load_average: LoadAverage, };
