// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrmDeal } from "./CrmDeal";
import type { ValidationWarning } from "./ValidationWarning";

export type TransitionResult = { deal: CrmDeal, warnings: Array<ValidationWarning>, agent_flow_id: string | null, cancel_deadline: string | null, actions_taken: Array<string>, };
