// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for creating/updating model pricing
 */
export type UpsertModelPricing = { model: string, provider: string, input_cost_per_million: bigint, output_cost_per_million: bigint, multiplier: number | null, };
