// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Register or update a model
 */
export type UpsertRouterModel = { name: string, model_id: string, provider: string, provider_base_url: string | null, api_key_env_var: string | null, priority: bigint | null, context_window: bigint | null, max_output_tokens: bigint | null, supports_tools: boolean | null, supports_vision: boolean | null, cost_per_million_input: bigint | null, cost_per_million_output: bigint | null, is_enabled: boolean | null, };
