// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * VIBE network configuration returned to the frontend
 */
export type VibeConfig = { revenue_address: string, network: string, vibe_token_address: string, };
