// This file was generated by `crates/core/src/bin/generate_types.rs`.

// Do not edit this file manually.

// If you are an AI, and you absolutely have to edit this file, please confirm with the user first.

export type DirectoryEntry = { name: string, path: string, is_directory: boolean, is_git_repo: boolean, last_modified: bigint | null, };

export type DirectoryListResponse = { entries: Array<DirectoryEntry>, current_path: string, };

export type Project = { id: string, name: string, git_repo_path: string, setup_script: string | null, dev_script: string | null, cleanup_script: string | null, copy_files: string | null, created_at: Date, updated_at: Date, };

export type CreateProject = { name: string, git_repo_path: string, use_existing_repo: boolean, setup_script: string | null, dev_script: string | null, cleanup_script: string | null, copy_files: string | null, };

export type UpdateProject = { name: string | null, git_repo_path: string | null, setup_script: string | null, dev_script: string | null, cleanup_script: string | null, copy_files: string | null, };

export type ProjectPod = { id: string, project_id: string, title: string, description: string, status: string, lead: string | null, created_at: Date, updated_at: Date, };

export type CreateProjectPod = { project_id: string, title: string, description?: string, status?: string, lead?: string, };

export type UpdateProjectPod = { title?: string, description?: string, status?: string, lead?: string, };

export type ProjectBoardType = "default" | "custom";

export type ProjectBoard = { id: string, project_id: string, name: string, slug: string, board_type: ProjectBoardType, description?: string | null, metadata?: string | null, created_at: string, updated_at: string, };

export type CreateProjectBoard = { project_id: string, name: string, slug: string, board_type: ProjectBoardType, description: string | null, metadata: string | null, };

export type UpdateProjectBoard = { name: string | null, slug: string | null, board_type: ProjectBoardType | null, description: string | null | null, metadata: string | null | null, };

export type ProjectAsset = { id: string, project_id: string, pod_id: string | null, board_id: string | null, category: string, scope: string, name: string, storage_path: string, checksum: string | null, byte_size: bigint | null, mime_type: string | null, metadata: string | null, uploaded_by: string | null, created_at: Date, updated_at: Date, };

export type CreateProjectAsset = { project_id: string, pod_id?: string, board_id?: string, category?: string, scope?: string, name: string, storage_path: string, checksum?: string, byte_size?: bigint, mime_type?: string, metadata?: string, uploaded_by?: string, };

export type UpdateProjectAsset = { pod_id?: string, board_id?: string, category?: string, scope?: string, name?: string, storage_path?: string, checksum?: string, byte_size?: bigint, mime_type?: string, metadata?: string, };

export type AgentWallet = { id: string, profile_key: string, display_name: string, budget_limit: number, spent_amount: number, created_at: Date, updated_at: Date, };

export type AgentWalletTransaction = { id: string, wallet_id: string, direction: string, amount: number, description: string, metadata: string | null, task_id: string | null, process_id: string | null, created_at: Date, };

export type UpsertAgentWallet = { profile_key: string, display_name?: string, budget_limit: number, };

export type CreateWalletTransaction = { wallet_id: string, direction: string, amount: number, description?: string, metadata?: string, task_id?: string, process_id?: string, };

export type SearchResult = { path: string, is_file: boolean, match_type: SearchMatchType, };

export type SearchMatchType = "FileName" | "DirectoryName" | "FullPath";

export type ExecutorAction = { typ: ExecutorActionType, next_action: ExecutorAction | null, };

export type McpConfig = { servers: { [key in string]?: JsonValue }, servers_path: Array<string>, template: JsonValue, preconfigured: JsonValue, is_toml_config: boolean, };

export type ExecutorActionType = { "type": "CodingAgentInitialRequest" } & CodingAgentInitialRequest | { "type": "CodingAgentFollowUpRequest" } & CodingAgentFollowUpRequest | { "type": "ScriptRequest" } & ScriptRequest;

export type ScriptContext = "SetupScript" | "CleanupScript" | "DevServer";

export type ScriptRequest = { script: string, language: ScriptRequestLanguage, context: ScriptContext, };

export type ScriptRequestLanguage = "Bash";

export enum BaseCodingAgent { CLAUDE_CODE = "CLAUDE_CODE", AMP = "AMP", GEMINI = "GEMINI", CODEX = "CODEX", DUCK = "DUCK", OPENCODE = "OPENCODE", CURSOR = "CURSOR", QWEN_CODE = "QWEN_CODE" }

export type CodingAgent = { "CLAUDE_CODE": ClaudeCode } | { "AMP": Amp } | { "GEMINI": Gemini } | { "CODEX": Codex } | { "DUCK": Duck } | { "OPENCODE": Opencode } | { "CURSOR": Cursor } | { "QWEN_CODE": QwenCode };

export type TaskTemplate = { id: string, project_id: string | null, title: string, description: string | null, template_name: string, created_at: string, updated_at: string, };

export type CreateTaskTemplate = { project_id: string | null, title: string, description: string | null, template_name: string, };

export type UpdateTaskTemplate = { title: string | null, description: string | null, template_name: string | null, };

export type TaskStatus = "todo" | "inprogress" | "inreview" | "done" | "cancelled";

export type Priority = "critical" | "high" | "medium" | "low";

export type ApprovalStatus = "pending" | "approved" | "rejected" | "changesrequested";

export type Task = { id: string, project_id: string, pod_id: string | null, board_id: string | null, title: string, description: string | null, status: TaskStatus, parent_task_attempt: string | null, created_at: string, updated_at: string, priority: Priority, assignee_id: string | null, assigned_agent: string | null, agent_id: string | null, assigned_mcps: string | null, created_by: string, requires_approval: boolean, approval_status: ApprovalStatus | null, parent_task_id: string | null, tags: string | null, due_date: string | null, custom_properties?: Record<string, unknown> | null, scheduled_start: string | null, scheduled_end: string | null, };

export type TaskWithAttemptStatus = { has_in_progress_attempt: boolean, has_merged_attempt: boolean, last_attempt_failed: boolean, executor: string, 
/**
 * Latest execution summary for the task (populated from most recent attempt)
 */
last_execution_summary: ExecutionSummaryBrief | null, 
/**
 * Collaborators who have worked on this task
 */
collaborators: Array<TaskCollaborator> | null, id: string, project_id: string, pod_id: string | null, board_id: string | null, title: string, description: string | null, status: TaskStatus, parent_task_attempt: string | null, created_at: string, updated_at: string, priority: Priority, assignee_id: string | null, assigned_agent: string | null, agent_id: string | null, assigned_mcps: string | null, created_by: string, requires_approval: boolean, approval_status: ApprovalStatus | null, parent_task_id: string | null, tags: string | null, due_date: string | null, custom_properties?: Record<string, unknown> | null, scheduled_start: string | null, scheduled_end: string | null, };

export type TaskRelationships = { parent_task: Task | null, current_attempt: TaskAttempt, children: Array<Task>, };

export type CreateTask = { project_id: string, pod_id?: string, board_id?: string, title: string, description: string | null, parent_task_attempt: string | null, image_ids: Array<string> | null, priority: Priority | null, assignee_id: string | null, assigned_agent: string | null, agent_id: string | null, assigned_mcps: Array<string> | null, created_by: string, requires_approval: boolean | null, parent_task_id: string | null, tags: Array<string> | null, due_date: string | null, custom_properties: Record<string, unknown> | null, scheduled_start: string | null, scheduled_end: string | null, };

export type UpdateTask = { title: string | null, description: string | null, status: TaskStatus | null, parent_task_attempt: string | null, image_ids: Array<string> | null, pod_id?: string | null, board_id?: string | null, priority: Priority | null, assignee_id: string | null, assigned_agent: string | null, agent_id: string | null | null, assigned_mcps: Array<string> | null, requires_approval: boolean | null, approval_status: ApprovalStatus | null, parent_task_id: string | null, tags: Array<string> | null, due_date: string | null, custom_properties: Record<string, unknown> | null, scheduled_start: string | null | null, scheduled_end: string | null | null, };

export type CustomFieldType = "text" | "number" | "date" | "url" | "checkbox" | "select" | "multi_select" | "formula" | "relationship" | "user" | "file" | "auto_increment";

export type CustomFieldDefinition = { id: string, project_id: string, name: string, field_type: CustomFieldType, required: boolean, options?: Record<string, unknown> | null, default_value?: unknown, metadata?: Record<string, unknown> | null, created_at: string, updated_at: string, };

export type CreateCustomFieldDefinition = { project_id: string, name: string, field_type: CustomFieldType, required: boolean, options: Record<string, unknown> | null, default_value: unknown, metadata: Record<string, unknown> | null, };

export type UpdateCustomFieldDefinition = { name: string | null, field_type: CustomFieldType | null, required: boolean | null, options: Record<string, unknown> | null, default_value: unknown, metadata: Record<string, unknown> | null, };

export type DependencyType = "blocks" | "relates_to";

export type TaskDependency = { id: string, project_id: string, source_task_id: string, target_task_id: string, dependency_type: DependencyType, created_at: string, };

export type CreateTaskDependency = { project_id: string, source_task_id: string, target_task_id: string, dependency_type: DependencyType, };

export type TimeEntry = { id: string, project_id: string, task_id: string, description?: string | null, start_time: string, end_time?: string | null, duration_seconds?: bigint | null, created_at: string, };

export type CreateTimeEntry = { project_id: string, task_id: string, description: string | null, start_time: string, end_time: string | null, duration_seconds: bigint | null, };

export type TaskComment = { id: string, task_id: string, author_id: string, author_type: AuthorType, content: string, comment_type: CommentType, parent_comment_id: string | null, mentions: string | null, metadata: string | null, created_at: string, };

export type CreateTaskComment = { task_id: string, author_id: string, author_type: AuthorType, content: string, comment_type: CommentType | null, parent_comment_id: string | null, mentions: Array<string> | null, metadata: JsonValue | null, };

export type AuthorType = "human" | "agent" | "mcp" | "system";

export type CommentType = "comment" | "statusupdate" | "review" | "approval" | "system" | "handoff" | "mcpnotification";

export type ActivityLog = { id: string, task_id: string, actor_id: string, actor_type: ActorType, action: string, previous_state: string | null, new_state: string | null, metadata: string | null, timestamp: string, };

export type CreateActivityLog = { task_id: string, actor_id: string, actor_type: ActorType, action: string, previous_state: JsonValue | null, new_state: JsonValue | null, metadata: JsonValue | null, };

export type ActorType = "human" | "agent" | "mcp" | "system";

export type Image = { id: string, file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, created_at: string, updated_at: string, };

export type CreateImage = { file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, };

export type ApiResponse<T, E = T> = { success: boolean, data: T | null, error_data: E | null, message: string | null, };

export type UserSystemInfo = { config: Config, environment: Environment, 
/**
 * Capabilities supported per executor (e.g., { "CLAUDE_CODE": ["SESSION_FORK"] })
 */
capabilities: { [key in string]?: Array<BaseAgentCapability> }, executors: { [key in BaseCodingAgent]?: ExecutorConfig }, };

export type Environment = { os_type: string, os_version: string, os_architecture: string, bitness: string, };

export type McpServerQuery = { executor: BaseCodingAgent, };

export type UpdateMcpServersBody = { servers: { [key in string]?: JsonValue }, };

export type GetMcpServerResponse = { mcp_config: McpConfig, config_path: string, };

export type CreateFollowUpAttempt = { prompt: string, variant: string | null, image_ids: Array<string> | null, };

export type FollowUpDraftResponse = { task_attempt_id: string, prompt: string, queued: boolean, variant: string | null, image_ids: Array<string> | null, version: bigint, };

export type UpdateFollowUpDraftRequest = { prompt: string | null, variant: string | null | null, image_ids: Array<string> | null, version: bigint | null, };

export type CreateAndStartTaskRequest = { task: CreateTask, executor_profile_id: ExecutorProfileId, base_branch: string, };

export type CreateGitHubPrRequest = { title: string, body: string | null, base_branch: string | null, };

export type ImageResponse = { id: string, file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, created_at: string, updated_at: string, };

export enum GitHubServiceError { TOKEN_INVALID = "TOKEN_INVALID", INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS", REPO_NOT_FOUND_OR_NO_ACCESS = "REPO_NOT_FOUND_OR_NO_ACCESS" }

export type Config = { config_version: string, theme: ThemeMode, executor_profile: ExecutorProfileId, disclaimer_acknowledged: boolean, onboarding_acknowledged: boolean, github_login_acknowledged: boolean, telemetry_acknowledged: boolean, notifications: NotificationConfig, editor: EditorConfig, github: GitHubConfig, analytics_enabled: boolean | null, workspace_dir: string | null, last_app_version: string | null, show_release_notes: boolean, language: UiLanguage, aptos_wallet: AptosWalletConfig, trello: TrelloConfig, airtable: AirtableConfig, };

export type NotificationConfig = { sound_enabled: boolean, push_enabled: boolean, sound_file: SoundFile, };

export enum ThemeMode { LIGHT = "LIGHT", DARK = "DARK", SYSTEM = "SYSTEM" }

export type EditorConfig = { editor_type: EditorType, custom_command: string | null, };

export enum EditorType { VS_CODE = "VS_CODE", CURSOR = "CURSOR", WINDSURF = "WINDSURF", INTELLI_J = "INTELLI_J", ZED = "ZED", XCODE = "XCODE", CUSTOM = "CUSTOM" }

export type GitHubConfig = { pat: string | null, oauth_token: string | null, username: string | null, primary_email: string | null, default_pr_base: string | null, };

export type AptosWalletConfig = { account_address: string, public_key: string, private_key: string, };

export enum SoundFile { ABSTRACT_SOUND1 = "ABSTRACT_SOUND1", ABSTRACT_SOUND2 = "ABSTRACT_SOUND2", ABSTRACT_SOUND3 = "ABSTRACT_SOUND3", ABSTRACT_SOUND4 = "ABSTRACT_SOUND4", COW_MOOING = "COW_MOOING", PHONE_VIBRATION = "PHONE_VIBRATION", ROOSTER = "ROOSTER" }

export type UiLanguage = "BROWSER" | "EN" | "JA" | "ES";

export type DeviceFlowStartResponse = { user_code: string, verification_uri: string, expires_in: number, interval: number, };

export enum DevicePollStatus { SLOW_DOWN = "SLOW_DOWN", AUTHORIZATION_PENDING = "AUTHORIZATION_PENDING", SUCCESS = "SUCCESS" }

export enum CheckTokenResponse { VALID = "VALID", INVALID = "INVALID" }

export type GitBranch = { name: string, is_current: boolean, is_remote: boolean, last_commit_date: Date, };

export type Diff = { change: DiffChangeKind, oldPath: string | null, newPath: string | null, oldContent: string | null, newContent: string | null, 
/**
 * True when file contents are intentionally omitted (e.g., too large)
 */
contentOmitted: boolean, 
/**
 * Optional precomputed stats for omitted content
 */
additions: number | null, deletions: number | null, };

export type DiffChangeKind = "added" | "deleted" | "modified" | "renamed" | "copied" | "permissionChange";

export type RepositoryInfo = { id: bigint, name: string, full_name: string, owner: string, description: string | null, clone_url: string, ssh_url: string, default_branch: string, private: boolean, };

export type CommandBuilder = { 
/**
 * Base executable command (e.g., "npx -y @anthropic-ai/claude-code@latest")
 */
base: string, 
/**
 * Optional parameters to append to the base command
 */
params: Array<string> | null, };

export type ExecutorProfileId = { 
/**
 * The executor type (e.g., "CLAUDE_CODE", "AMP")
 */
executor: BaseCodingAgent, 
/**
 * Optional variant name (e.g., "PLAN", "ROUTER")
 */
variant: string | null, };

export type ExecutorConfig = { [key in string]?: { "CLAUDE_CODE": ClaudeCode } | { "AMP": Amp } | { "GEMINI": Gemini } | { "CODEX": Codex } | { "DUCK": Duck } | { "OPENCODE": Opencode } | { "CURSOR": Cursor } | { "QWEN_CODE": QwenCode } };

export type BaseAgentCapability = "SESSION_FORK";

export type ClaudeCode = { append_prompt: AppendPrompt, claude_code_router?: boolean | null, plan?: boolean | null, approvals?: boolean | null, model?: string | null, dangerously_skip_permissions?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, };

export type Gemini = { append_prompt: AppendPrompt, model: GeminiModel, yolo?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, };

export type GeminiModel = "default" | "flash";

export type Amp = { append_prompt: AppendPrompt, dangerously_allow_all?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, };

export type Codex = { append_prompt: AppendPrompt, sandbox?: SandboxMode | null, oss?: boolean | null, model?: string | null, model_reasoning_effort?: ReasoningEffort | null, model_reasoning_summary?: ReasoningSummary | null, base_command_override?: string | null, additional_params?: Array<string> | null, };

export type SandboxMode = "auto" | "read-only" | "workspace-write" | "danger-full-access";

export type ReasoningEffort = "low" | "medium" | "high";

export type ReasoningSummary = "auto" | "concise" | "detailed" | "none";

export type Duck = { append_prompt: AppendPrompt, sandbox?: SandboxMode | null, oss?: boolean | null, model?: string | null, model_reasoning_effort?: ReasoningEffort | null, model_reasoning_summary?: ReasoningSummary | null, base_command_override?: string | null, additional_params?: Array<string> | null, };

export type Cursor = { append_prompt: AppendPrompt, force?: boolean | null, model?: string | null, base_command_override?: string | null, additional_params?: Array<string> | null, };

export type Opencode = { append_prompt: AppendPrompt, model?: string | null, agent?: string | null, base_command_override?: string | null, additional_params?: Array<string> | null, };

export type QwenCode = { append_prompt: AppendPrompt, yolo?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, };

export type AppendPrompt = string | null;

export type CodingAgentInitialRequest = { prompt: string, 
/**
 * Executor profile specification
 */
executor_profile_id: ExecutorProfileId, };

export type CodingAgentFollowUpRequest = { prompt: string, session_id: string, 
/**
 * Executor profile specification
 */
executor_profile_id: ExecutorProfileId, };

export type CreateTaskAttemptBody = { task_id: string, 
/**
 * Executor profile specification
 */
executor_profile_id: ExecutorProfileId, base_branch: string, };

export type RebaseTaskAttemptRequest = { new_base_branch: string | null, };

export type GitOperationError = { "type": "merge_conflicts", message: string, op: ConflictOp, } | { "type": "rebase_in_progress" };

export type ReplaceProcessRequest = { 
/**
 * Process to replace (delete this and later ones)
 */
process_id: string, 
/**
 * New prompt to use for the replacement follow-up
 */
prompt: string, 
/**
 * Optional variant override
 */
variant: string | null, 
/**
 * If true, allow resetting Git even when uncommitted changes exist
 */
force_when_dirty: boolean | null, 
/**
 * If false, skip performing the Git reset step (history drop still applies)
 */
perform_git_reset: boolean | null, };

export type CommitInfo = { sha: string, subject: string, };

export type BranchStatus = { commits_behind: number | null, commits_ahead: number | null, has_uncommitted_changes: boolean | null, head_oid: string | null, uncommitted_count: number | null, untracked_count: number | null, base_branch_name: string, remote_commits_behind: number | null, remote_commits_ahead: number | null, merges: Array<Merge>, 
/**
 * True if a `git rebase` is currently in progress in this worktree
 */
is_rebase_in_progress: boolean, 
/**
 * Current conflict operation if any
 */
conflict_op: ConflictOp | null, 
/**
 * List of files currently in conflicted (unmerged) state
 */
conflicted_files: Array<string>, };

export type ConflictOp = "rebase" | "merge" | "cherry_pick" | "revert";

export type TaskAttempt = { id: string, task_id: string, container_ref: string | null, branch: string | null, base_branch: string, executor: string, worktree_deleted: boolean, setup_completed_at: string | null, created_at: string, updated_at: string, };

export type ExecutionProcess = { id: string, task_attempt_id: string, run_reason: ExecutionProcessRunReason, executor_action: ExecutorAction, 
/**
 * Git HEAD commit OID captured before the process starts
 */
before_head_commit: string | null, 
/**
 * Git HEAD commit OID captured after the process ends
 */
after_head_commit: string | null, status: ExecutionProcessStatus, exit_code: bigint | null, 
/**
 * dropped: true if this process is excluded from the current
 * history view (due to restore/trimming). Hidden from logs/timeline;
 * still listed in the Processes tab.
 */
dropped: boolean, started_at: string, completed_at: string | null, created_at: string, updated_at: string, };

export type ExecutionProcessStatus = "running" | "completed" | "failed" | "killed";

export type ExecutionProcessRunReason = "setupscript" | "cleanupscript" | "codingagent" | "devserver";

export type ExecutionSummary = { id: string, task_attempt_id: string, execution_process_id: string | null, files_modified: number, files_created: number, files_deleted: number, commands_run: number, commands_failed: number, 
/**
 * JSON array of tool names used during execution
 */
tools_used: string | null, completion_status: CompletionStatus, blocker_summary: string | null, error_summary: string | null, execution_time_ms: bigint, human_rating: number | null, human_notes: string | null, is_reference_example: boolean, workflow_tags: string | null, created_at: string, updated_at: string, };

export type CompletionStatus = "full" | "partial" | "blocked" | "failed";

export type CreateExecutionSummary = { task_attempt_id: string, execution_process_id: string | null, files_modified: number, files_created: number, files_deleted: number, commands_run: number, commands_failed: number, tools_used: Array<string> | null, completion_status: CompletionStatus, blocker_summary: string | null, error_summary: string | null, execution_time_ms: bigint, workflow_tags: Array<string> | null, };

export type UpdateExecutionSummaryFeedback = { human_rating: number | null, human_notes: string | null, is_reference_example: boolean | null, };

export type ExecutionSummaryBrief = { files_modified: number, files_created: number, commands_failed: number, completion_status: CompletionStatus, tools_used: Array<string> | null, human_rating: number | null, execution_time_ms: bigint, };

export type TaskCollaborator = { actor_id: string, actor_type: string, last_action: string, last_action_at: string, };

export type Agent = { id: string, wallet_address: string | null, short_name: string, designation: string, description: string | null, personality: string | null, voice_style: string | null, avatar_url: string | null, capabilities: string | null, tools: string | null, functions: string | null, default_model: string | null, fallback_models: string | null, model_config: string | null, status: AgentStatus, autonomy_level: AutonomyLevel, max_concurrent_tasks: bigint | null, priority_weight: bigint | null, tasks_completed: bigint | null, tasks_failed: bigint | null, total_execution_time_ms: bigint | null, average_rating: number | null, version: string | null, created_at: string, updated_at: string, created_by: string | null, parent_agent_id: string | null, team_id: string | null, };

export type AgentStatus = "active" | "inactive" | "maintenance" | "training";

export type AutonomyLevel = "full" | "supervised" | "approval_required" | "manual";

export type ProficiencyLevel = "novice" | "standard" | "expert" | "master";

export type AgentPersonality = { 
/**
 * Core personality traits (e.g., "analytical", "creative", "methodical")
 */
traits: Array<string>, 
/**
 * Communication style (e.g., "formal", "casual", "technical")
 */
communication_style: string, 
/**
 * How the agent approaches problems
 */
problem_solving_approach: string, 
/**
 * Preferred interaction patterns
 */
interaction_preferences: Array<string>, 
/**
 * Agent's "backstory" or character description
 */
backstory: string | null, 
/**
 * Catchphrases or signature expressions
 */
signature_phrases: Array<string>, 
/**
 * Emotional baseline (e.g., "calm", "enthusiastic", "focused")
 */
emotional_baseline: string, };

export type AgentFunction = { name: string, description: string, parameters: JsonValue, required_tools: Array<string>, example_usage: string | null, };

export type AgentWithParsedFields = { id: string, wallet_address: string | null, short_name: string, designation: string, description: string | null, personality: AgentPersonality | null, voice_style: string | null, avatar_url: string | null, capabilities: Array<string> | null, tools: Array<string> | null, functions: Array<AgentFunction> | null, default_model: string | null, fallback_models: Array<string> | null, model_config: JsonValue | null, status: AgentStatus, autonomy_level: AutonomyLevel, max_concurrent_tasks: bigint | null, priority_weight: bigint | null, tasks_completed: bigint | null, tasks_failed: bigint | null, average_rating: number | null, version: string | null, created_at: string, updated_at: string, };

export type CreateAgent = { wallet_address: string | null, short_name: string, designation: string, description: string | null, personality: AgentPersonality | null, voice_style: string | null, avatar_url: string | null, capabilities: Array<string> | null, tools: Array<string> | null, functions: Array<AgentFunction> | null, default_model: string | null, fallback_models: Array<string> | null, model_config: JsonValue | null, status: AgentStatus | null, autonomy_level: AutonomyLevel | null, max_concurrent_tasks: bigint | null, priority_weight: bigint | null, parent_agent_id: string | null, team_id: string | null, created_by: string | null, };

export type UpdateAgent = { wallet_address: string | null, short_name: string | null, designation: string | null, description: string | null, personality: AgentPersonality | null, voice_style: string | null, avatar_url: string | null, capabilities: Array<string> | null, tools: Array<string> | null, functions: Array<AgentFunction> | null, default_model: string | null, fallback_models: Array<string> | null, model_config: JsonValue | null, status: AgentStatus | null, autonomy_level: AutonomyLevel | null, max_concurrent_tasks: bigint | null, priority_weight: bigint | null, };

export type AgentBrief = { id: string, short_name: string, designation: string, avatar_url: string | null, status: AgentStatus, };

export type Merge = { "type": "direct" } & DirectMerge | { "type": "pr" } & PrMerge;

export type DirectMerge = { id: string, task_attempt_id: string, merge_commit: string, target_branch_name: string, created_at: string, };

export type PrMerge = { id: string, task_attempt_id: string, created_at: string, target_branch_name: string, pr_info: PullRequestInfo, };

export type MergeStatus = "open" | "merged" | "closed" | "unknown";

export type PullRequestInfo = { number: bigint, url: string, status: MergeStatus, merged_at: string | null, merge_commit_sha: string | null, };

export type FollowUpDraft = { id: string, task_attempt_id: string, prompt: string, queued: boolean, sending: boolean, variant: string | null, image_ids: Array<string> | null, created_at: string, updated_at: string, version: bigint, };

export type CommandExitStatus = { "type": "exit_code", code: number, } | { "type": "success", success: boolean, };

export type CommandRunResult = { exit_status: CommandExitStatus | null, output: string | null, };

export type NormalizedEntry = { timestamp: string | null, entry_type: NormalizedEntryType, content: string, };

export type NormalizedEntryType = { "type": "user_message" } | { "type": "assistant_message" } | { "type": "tool_use", tool_name: string, action_type: ActionType, status: ToolStatus, } | { "type": "system_message" } | { "type": "error_message" } | { "type": "thinking" } | { "type": "loading" };

export type FileChange = { "action": "write", content: string, } | { "action": "delete" } | { "action": "rename", new_path: string, } | { "action": "edit", 
/**
 * Unified diff containing file header and hunks.
 */
unified_diff: string, 
/**
 * Whether line number in the hunks are reliable.
 */
has_line_numbers: boolean, };

export type ActionType = { "action": "file_read", path: string, } | { "action": "file_edit", path: string, changes: Array<FileChange>, } | { "action": "command_run", command: string, result: CommandRunResult | null, } | { "action": "search", query: string, } | { "action": "web_fetch", url: string, } | { "action": "tool", tool_name: string, arguments: JsonValue | null, result: ToolResult | null, } | { "action": "task_create", description: string, } | { "action": "plan_presentation", plan: string, } | { "action": "todo_management", todos: Array<TodoItem>, operation: string, } | { "action": "other", description: string, };

export type TodoItem = { content: string, status: string, priority: string | null, };

export type ToolResult = { type: ToolResultValueType, 
/**
 * For Markdown, this will be a JSON string; for JSON, a structured value
 */
value: JsonValue, };

export type ToolResultValueType = { "type": "markdown" } | { "type": "json" };

export type ToolStatus = { "status": "created" } | { "status": "success" } | { "status": "failed" } | { "status": "denied", reason: string | null, } | { "status": "pending_approval", approval_id: string, requested_at: string, timeout_at: string, } | { "status": "timed_out" };

export type PatchType = { "type": "NORMALIZED_ENTRY", "content": NormalizedEntry } | { "type": "STDOUT", "content": string } | { "type": "STDERR", "content": string } | { "type": "DIFF", "content": Diff };

export type ToolApprovalStatus = { "status": "pending" } | { "status": "approved" } | { "status": "denied", reason?: string, } | { "status": "timed_out" };

export type CreateApprovalRequest = { tool_name: string, tool_input: JsonValue, session_id: string, };

export type ApprovalResponse = { execution_process_id: string, status: ToolApprovalStatus, };

export type UserListItem = { id: string, username: string, email: string, full_name: string, avatar_url: string | null, is_active: number, is_admin: number, last_login_at: string | null, created_at: string, };

export type UserDetail = { id: string, username: string, email: string, full_name: string, avatar_url: string | null, is_active: number, is_admin: number, last_login_at: string | null, created_at: string, updated_at: string, };

export type UpdateUserRequest = { full_name: string | null, email: string | null, avatar_url: string | null, };

export type UpdateRoleRequest = { is_admin: boolean, };

export type CreateUserRequest = { username: string, password: string, email: string | null, full_name: string, is_admin: boolean, };

export type CreateUserResponse = { message: string, user_id: string, username: string, };

export type ProjectMemberItem = { id: string, project_id: string, user_id: string, username: string, full_name: string, email: string, avatar_url: string | null, role: string, granted_at: string, granted_by_username: string | null, };

export type AddProjectMemberRequest = { user_id: string, role: string, };

export type UpdateMemberRoleRequest = { role: string, };

export type ProjectAccessResponse = { has_access: boolean, role: string | null, can_read: boolean, can_write: boolean, can_manage_members: boolean, can_delete: boolean, };

export type MyProjectItem = { project_id: string, project_name: string, role: string, granted_at: string, };

export type GraphPlan = { id: string, title: string, requestId: string, sessionId: string, createdAt: string, status: GraphPlanStatus, nodes: Array<GraphNode>, edges: Array<GraphEdge>, };

export type GraphPlanSummary = { id: string, title: string, createdAt: string, status: GraphPlanStatus, nodeCount: number, };

export type GraphPlanStatus = "pending" | "inProgress" | "completed" | "failed";

export type GraphNode = { id: string, label: string, agent: string | null, description: string | null, status: GraphNodeStatus, metadata: JsonValue, };

export type GraphNodeStatus = "pending" | "running" | "completed" | "failed";

export type GraphEdge = { fromNode: string, toNode: string, };

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null;

export type AirtableBase = { id: string, project_id: string, airtable_base_id: string, airtable_base_name: string | null, sync_enabled: boolean, default_table_id: string | null, last_synced_at: string | null, created_at: string, updated_at: string, };

export type CreateAirtableBase = { project_id: string, airtable_base_id: string, airtable_base_name: string | null, default_table_id: string | null, };

export type UpdateAirtableBase = { airtable_base_name: string | null, sync_enabled: boolean | null, default_table_id: string | null, };

export type AirtableRecordLink = { id: string, task_id: string, airtable_record_id: string, airtable_base_id: string, airtable_table_id: string | null, origin: string, sync_status: string, last_sync_error: string | null, airtable_record_url: string | null, last_synced_at: string | null, created_at: string, updated_at: string, };

export type CreateAirtableRecordLink = { task_id: string, airtable_record_id: string, airtable_base_id: string, airtable_table_id: string | null, origin: AirtableOrigin, airtable_record_url: string | null, };

export type AirtableOrigin = "airtable" | "pcg";

export type AirtableSyncStatus = "synced" | "pending_push" | "pending_pull" | "error";

export type AirtableBaseInfo = { id: string, name: string, permissionLevel: string, };

export type AirtableTable = { id: string, name: string, primaryFieldId: string | null, fields: Array<AirtableField>, views: Array<AirtableView>, };

export type AirtableField = { id: string, name: string, type: string, options: JsonValue | null, };

export type AirtableView = { id: string, name: string, type: string, };

export type AirtableRecord = { id: string, fields: JsonValue, createdTime: string, };

export type AirtableRecordUpdate = { fields: JsonValue, };

export type AirtableUserInfo = { id: string, email: string | null, };

export type AirtableComment = { id: string, author: AirtableCommentAuthor, text: string, createdTime: string, };

export type AirtableCommentAuthor = { id: string, email: string | null, name: string | null, };

export type AirtableServiceError = "NOT_CONFIGURED" | "AUTH_FAILED" | "RATE_LIMITED" | { "BASE_NOT_FOUND": string } | { "RECORD_NOT_FOUND": string } | { "TABLE_NOT_FOUND": string } | { "API_ERROR": string };

export type TrelloConfig = { 
/**
 * Trello API key (from https://trello.com/app-key)
 */
api_key: string | null, 
/**
 * Trello token (OAuth token for user access)
 */
token: string | null, 
/**
 * Cached Trello username for display
 */
username: string | null, 
/**
 * Sync deliverables as comments on Trello cards
 */
sync_deliverables_as_comments: boolean, 
/**
 * Auto-import new cards when syncing
 */
auto_import_new_cards: boolean, };

export type AirtableConfig = { 
/**
 * Airtable Personal Access Token
 */
token: string | null, 
/**
 * Cached Airtable user email for display
 */
user_email: string | null, 
/**
 * Sync deliverables as comments on Airtable records
 */
sync_deliverables_as_comments: boolean, 
/**
 * Auto-import new records when syncing
 */
auto_import_new_records: boolean, };

export type AirtableVerifyRequest = { token: string, };

export type AirtableVerifyResponse = { user_email: string | null, valid: boolean, };

export type AirtableProjectQuery = { project_id: string | null, };

export type AirtableTableQuery = { table_id: string | null, };

export type AirtableImportRequest = { table_id: string, project_id: string, board_id: string | null, 
/**
 * The field name to use as task title (defaults to first text field)
 */
title_field: string | null, 
/**
 * The field name to use as task description (optional)
 */
description_field: string | null, };

export type AirtableImportResult = { imported_count: number, skipped_count: number, tasks: Array<AirtableTaskWithLink>, };

export type AirtableTaskWithLink = { task: Task, airtable_link: AirtableRecordLink, };

export type AirtablePushTaskRequest = { table_id: string, base_id: string, 
/**
 * Field name to store the task title
 */
title_field: string | null, 
/**
 * Field name to store the task description
 */
description_field: string | null, };

export type AirtableConnectionWithBase = { connection: AirtableBase, base_info: AirtableBaseInfo | null, };

export type FlowType = "content_creation" | "research" | "engagement" | "scheduling" | "campaign" | "analysis" | "monitoring" | "custom";

export type FlowStatus = "planning" | "executing" | "verifying" | "completed" | "failed" | "paused" | "awaiting_approval";

export type AgentPhase = "planning" | "execution" | "verification";

export type AgentFlow = { id: string, task_id: string, flow_type: FlowType, status: FlowStatus, planner_agent_id: string | null, executor_agent_id: string | null, verifier_agent_id: string | null, current_phase: AgentPhase, planning_started_at: string | null, planning_completed_at: string | null, execution_started_at: string | null, execution_completed_at: string | null, verification_started_at: string | null, verification_completed_at: string | null, flow_config: string | null, handoff_instructions: string | null, verification_score: number | null, human_approval_required: boolean, approved_by: string | null, approved_at: string | null, created_at: string, updated_at: string, };

export type CreateAgentFlow = { task_id: string, flow_type: FlowType, planner_agent_id: string | null, executor_agent_id: string | null, verifier_agent_id: string | null, flow_config: JsonValue | null, human_approval_required: boolean | null, };

export type UpdateAgentFlow = { status: FlowStatus | null, current_phase: AgentPhase | null, planner_agent_id: string | null, executor_agent_id: string | null, verifier_agent_id: string | null, handoff_instructions: string | null, verification_score: number | null, approved_by: string | null, };

export type FlowEventType = "phase_started" | "phase_completed" | "artifact_created" | "artifact_updated" | "approval_requested" | "approval_decision" | "wide_research_started" | "subagent_progress" | "wide_research_completed" | "agent_handoff" | "flow_paused" | "flow_resumed" | "flow_failed" | "flow_completed";

export type FlowEventPayload = { "type": "PhaseStarted", phase: string, agent_id: string | null, } | { "type": "PhaseCompleted", phase: string, artifacts_produced: Array<string>, } | { "type": "ArtifactCreated", artifact_id: string, artifact_type: string, title: string, phase: string, } | { "type": "ArtifactUpdated", artifact_id: string, changes: JsonValue, } | { "type": "ApprovalRequested", artifact_id: string, requested_by_agent: string | null, approval_type: string, } | { "type": "ApprovalDecision", artifact_id: string, decision: string, reviewer_id: string | null, feedback: string | null, } | { "type": "WideResearchStarted", session_id: string, total_subagents: number, } | { "type": "SubagentProgress", session_id: string, subagent_id: string, subagent_index: number, target_item: string, status: string, result_artifact_id: string | null, } | { "type": "WideResearchCompleted", session_id: string, aggregated_artifact_id: string, total_completed: number, total_failed: number, } | { "type": "AgentHandoff", from_agent_id: string | null, to_agent_id: string | null, from_phase: string, to_phase: string, handoff_artifact_id: string | null, instructions: string | null, } | { "type": "FlowPaused", reason: string | null, paused_by: string | null, } | { "type": "FlowResumed", resumed_by: string | null, } | { "type": "FlowFailed", error: string, phase: string, } | { "type": "FlowCompleted", verification_score: number | null, total_artifacts: number, };

export type AgentFlowEvent = { id: string, agent_flow_id: string, event_type: FlowEventType, event_data: string, created_at: string, };

export type ResearchSessionStatus = "spawning" | "in_progress" | "aggregating" | "completed" | "failed" | "cancelled";

export type SubagentStatus = "pending" | "running" | "completed" | "failed" | "timeout" | "cancelled";

export type WideResearchSession = { id: string, agent_flow_id: string | null, parent_agent_id: string | null, task_description: string, total_subagents: number, completed_subagents: number, failed_subagents: number, status: ResearchSessionStatus, parallelism_limit: number | null, timeout_per_subagent: number | null, aggregated_result_artifact_id: string | null, created_at: string, completed_at: string | null, };

export type WideResearchSubagent = { id: string, session_id: string, subagent_index: number, target_item: string, target_metadata: string | null, status: SubagentStatus, execution_process_id: string | null, result_artifact_id: string | null, error_message: string | null, started_at: string | null, completed_at: string | null, };

export type CreateWideResearchSession = { agent_flow_id: string | null, parent_agent_id: string | null, task_description: string, targets: Array<ResearchTarget>, parallelism_limit: number | null, timeout_per_subagent: number | null, };

export type ResearchTarget = { target_item: string, metadata: JsonValue | null, };

export type ReviewType = "approval" | "feedback" | "revision_request" | "quality_check" | "compliance_check";

export type ReviewStatus = "pending" | "approved" | "rejected" | "revision_requested" | "acknowledged";

export type ArtifactReview = { id: string, artifact_id: string, reviewer_id: string | null, reviewer_agent_id: string | null, reviewer_name: string | null, review_type: ReviewType, status: ReviewStatus, feedback_text: string | null, rating: number | null, revision_notes: string | null, revision_deadline: string | null, created_at: string, resolved_at: string | null, resolved_by: string | null, };

export type CreateArtifactReview = { artifact_id: string, reviewer_id: string | null, reviewer_agent_id: string | null, reviewer_name: string | null, review_type: ReviewType, feedback_text: string | null, rating: number | null, revision_notes: JsonValue | null, revision_deadline: string | null, };

export type ResolveReview = { status: ReviewStatus, feedback_text: string | null, rating: number | null, resolved_by: string, };

export type ArtifactRole = "primary" | "supporting" | "verification" | "reference";

export type TaskArtifact = { task_id: string, artifact_id: string, artifact_role: ArtifactRole, display_order: number, pinned: boolean, added_at: string, added_by: string | null, };

export type LinkArtifactToTask = { task_id: string, artifact_id: string, artifact_role: ArtifactRole | null, display_order: number | null, pinned: boolean | null, added_by: string | null, };

export type ArtifactType = "plan" | "screenshot" | "walkthrough" | "diff_summary" | "test_result" | "checkpoint" | "error_report" | "research_report" | "strategy_document" | "content_calendar" | "competitor_analysis" | "content_draft" | "visual_brief" | "schedule_manifest" | "engagement_log" | "verification_report" | "browser_recording" | "compliance_score" | "platform_screenshot" | "subagent_result" | "aggregated_research";

export type ArtifactPhase = "planning" | "execution" | "verification";

export type ArtifactReviewStatus = "none" | "pending" | "approved" | "rejected" | "revision_requested";

export type ExecutionArtifact = { id: string, execution_process_id: string, artifact_type: ArtifactType, title: string, content: string | null, file_path: string | null, metadata: string | null, created_at: string, };

export type BrandVoice = "formal" | "casual" | "playful" | "authoritative";

export type BrandProfile = { id: string, projectId: string, tagline: string | null, industry: string | null, primaryColor: string, secondaryColor: string, brandVoice: string | null, targetAudience: string | null, logoAssetId: string | null, guidelinesAssetId: string | null, createdAt: Date, updatedAt: Date, };

export type UpsertBrandProfile = { tagline: string | null, industry: string | null, primaryColor: string | null, secondaryColor: string | null, brandVoice: string | null, targetAudience: string | null, logoAssetId: string | null, guidelinesAssetId: string | null, };

export type AgentChatRequest = { 
/**
 * The message content
 */
message: string, 
/**
 * Session identifier for conversation continuity
 */
sessionId: string, 
/**
 * Optional project context
 */
projectId: string | null, 
/**
 * Optional additional context
 */
context: JsonValue | null, 
/**
 * Enable streaming response
 */
stream: boolean, };

export type AgentChatResponse = { 
/**
 * The agent's response content
 */
content: string, 
/**
 * Conversation ID for reference
 */
conversationId: string, 
/**
 * Agent information
 */
agentName: string, agentDesignation: string, 
/**
 * Token usage (if available)
 */
inputTokens: bigint | null, outputTokens: bigint | null, 
/**
 * Model used for this response
 */
model: string | null, provider: string | null, 
/**
 * Response latency in milliseconds
 */
latencyMs: bigint, };

export type ConversationSummary = { id: string, title: string | null, status: string, messageCount: bigint, lastMessageAt: string | null, createdAt: string, };