// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountStats = { account_id: string, email_address: string, total: bigint, unread: bigint, };
