// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An artifact produced by the agent
 */
export type AgentArtifact = { id: string, artifact_type: string, title: string, content: string | null, };
