// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentArtifact } from "./AgentArtifact";
import type { AgentResponseStatus } from "./AgentResponseStatus";
import type { ClarificationRequest } from "./ClarificationRequest";

/**
 * Structured response envelope from agent execution.
 * Agents should use the `submit_response` tool to return this format.
 */
export type AgentResponse = { status: AgentResponseStatus, message: string, artifacts: Array<AgentArtifact>, clarification: ClarificationRequest | null, };
