// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of an agent's structured response
 */
export type AgentResponseStatus = "success" | "partial" | "needs_clarification" | "failed";
