// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowEventType } from "./FlowEventType";

export type AgentFlowEvent = { id: string, agent_flow_id: string, event_type: FlowEventType, event_data: string, created_at: string, };
