// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentResponseStatus } from "./AgentResponseStatus";
import type { ClarificationRequest } from "./ClarificationRequest";

/**
 * Structured envelope wrapping all agent flow outputs.
 * The orchestration engine inspects `status` to decide next steps.
 */
export type AgentResponseEnvelope = { 
/**
 * Outcome of this agent step
 */
status: AgentResponseStatus, 
/**
 * Human-readable summary of what happened
 */
summary: string, 
/**
 * Structured output data (step-specific)
 */
data: Record<string, unknown> | null, 
/**
 * If status is NeedsClarification, the clarification request details
 */
clarification: ClarificationRequest | null, 
/**
 * Suggested next action for the orchestration engine
 */
suggested_next: string | null, 
/**
 * Confidence score (0.0 - 1.0) for the agent's output
 */
confidence: number | null, };
