// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPhase } from "./AgentPhase";
import type { FlowStatus } from "./FlowStatus";
import type { FlowType } from "./FlowType";

export type AgentFlow = { id: string, task_id: string, flow_type: FlowType, status: FlowStatus, planner_agent_id: string | null, executor_agent_id: string | null, verifier_agent_id: string | null, current_phase: AgentPhase, planning_started_at: string | null, planning_completed_at: string | null, execution_started_at: string | null, execution_completed_at: string | null, verification_started_at: string | null, verification_completed_at: string | null, flow_config: string | null, handoff_instructions: string | null, verification_score: number | null, human_approval_required: boolean, approved_by: string | null, approved_at: string | null, 
/**
 * JSON-serialized ClarificationRequest when status = NeedsClarification
 */
clarification_request: string | null, 
/**
 * Link to CRM deal (for pipeline-triggered agent flows)
 */
crm_deal_id: string | null, 
/**
 * Link to project (for task-execution flows)
 */
project_id: string | null, 
/**
 * Agent auto-start can be cancelled before this deadline
 */
cancel_deadline: string | null, 
/**
 * Number of retry attempts for this flow
 */
retry_count: number, 
/**
 * Last error message from a failed execution attempt
 */
last_error: string | null, created_at: string, updated_at: string, };
