// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agent wallet for tracking VIBE budget and spending
 * Note: On-chain operations are handled at the project/treasury level, not per-agent
 */
export type AgentWallet = { id: string, profile_key: string, display_name: string, 
/**
 * APT budget limit in octas (legacy, not used)
 */
budget_limit: number, 
/**
 * APT spent amount in octas (legacy, not used)
 */
spent_amount: number, 
/**
 * VIBE budget limit (1 VIBE = $0.01 USD)
 */
vibe_budget_limit: number | null, 
/**
 * VIBE spent amount
 */
vibe_spent_amount: number, created_at: Date, updated_at: Date, };
