// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentCostRow = { agent_id: string | null, agent_name: string, total_vibe: number, total_cost_cents: number, transaction_count: number, };
