// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewStatus } from "./ReviewStatus";
import type { ReviewType } from "./ReviewType";

export type ArtifactReview = { id: string, artifact_id: string, reviewer_id: string | null, reviewer_agent_id: string | null, reviewer_name: string | null, review_type: ReviewType, status: ReviewStatus, feedback_text: string | null, rating: number | null, revision_notes: string | null, revision_deadline: string | null, created_at: string, resolved_at: string | null, resolved_by: string | null, };
