// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Axis-aligned bounding box with optional rotation (degrees, clockwise).
 */
export type BBox = { x: number, y: number, w: number, h: number, rotation?: number, };
