// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BoardShare = { id: string, board_id: string, source_organization_id: string, target_organization_id: string, permission: string, share_type: string, shared_by: string, is_active: boolean, created_at: string, updated_at: string, };
