// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Project brand profile - stores brand identity data
 */
export type BrandProfile = { id: string, projectId: string, tagline: string | null, industry: string | null, primaryColor: string, secondaryColor: string, brandVoice: string | null, targetAudience: string | null, logoAssetId: string | null, guidelinesAssetId: string | null, createdAt: Date, updatedAt: Date, };
