// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Brand voice options for project identity
 */
export type BrandVoice = "formal" | "casual" | "playful" | "authoritative";
