// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CallStats = { total: bigint, inbound: bigint, outbound: bigint, completed: bigint, missed: bigint, total_duration_seconds: bigint, };
