// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CallStatus = "queued" | "ringing" | "in_progress" | "completed" | "busy" | "failed" | "no_answer" | "canceled";
