// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canvas metadata. Stored inside `deck_documents.canvas_json`.
 */
export type Canvas = { width: number, height: number, 
/**
 * `px` | `pt`.
 */
unit: string, dpi: number, };
