// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for clarification from the user
 */
export type ClarificationRequest = { question: string, context: string | null, required_fields: Array<string>, };
