// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Details of a clarification request from an agent
 */
export type ClarificationRequest = { 
/**
 * What the agent needs to know
 */
question: string, 
/**
 * Why this information is needed
 */
context: string | null, 
/**
 * Suggested options (if applicable)
 */
options: Array<string> | null, 
/**
 * Whether this blocks all progress or just this step
 */
blocking: boolean, };
