// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientMember = { id: string, client_id: string, user_id: string, role: string, granted_by: string | null, granted_at: string, };
