// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Client = { id: string, organization_id: string, name: string, slug: string, description: string | null, logo_url: string | null, website: string | null, crm_contact_id: string | null, is_active: boolean, created_at: Date, updated_at: Date, deleted_at: string | null, deleted_by: string | null, 
/**
 * UUID of the linked company in the Knowledge Graph
 */
company_id: string | null, 
/**
 * UUID of the primary person/contact in the Knowledge Graph
 */
primary_person_id: string | null, 
/**
 * When this lead first entered the pipeline (became a prospect)
 */
prospect_at: string | null, 
/**
 * When first payment received / deal won (becomes a client)
 */
client_since: string | null, vibe_budget_limit: number | null, vibe_spent_amount: number, };
