// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Client = { id: string, organization_id: string, name: string, slug: string, description: string | null, logo_url: string | null, website: string | null, crm_contact_id: string | null, is_active: boolean, created_at: Date, updated_at: Date, deleted_at: string | null, deleted_by: string | null, };
