// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client engagement type
 */
export type ClientType = "foundation_build" | "managed_growth" | "custom";
