// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CloudStorageAccount = { id: string, organization_id: string, project_id?: string, integration_connection_id?: string, provider: string, account_email?: string, display_name?: string, sync_cursor?: string, sync_root_path?: string, auto_sync: boolean, sync_interval_secs: bigint, last_sync_at?: Date | null, last_error?: string, status: string, total_files_synced: bigint, metadata: string, created_at: Date, updated_at: Date, };
