// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RGBA color, optionally linked back to a design token name.
 */
export type Color = { r: number, g: number, b: number, a: number, token?: string, };
