// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A real-world company as a public knowledge-graph entity.
 * Distinct from `organizations` (which is a company INSIDE the platform).
 * When a company joins the platform, `organization_id` is set.
 */
export type Company = { id: string, name: string, slug: string | null, website: string | null, industry: string | null, description: string | null, logo_url: string | null, cover_image_url: string | null, headquarters: string | null, address: string | null, city: string | null, country: string | null, phone: string | null, email: string | null, whatsapp: string | null, instagram_handle: string | null, linkedin_url: string | null, twitter_handle: string | null, facebook_url: string | null, founded_year: number | null, employee_count: string | null, tags: string | null, business_hours: string | null, notes: string | null, gmb_rating: number | null, gmb_review_count: number | null, gmb_place_id: string | null, intelligence_summary: string | null, intelligence_raw: string | null, intelligence_status: string, intelligence_last_run_at: string | null, intelligence_confidence: number | null, intelligence_agent: string | null, organization_id: string | null, created_by_org_id: string | null, created_at: string, updated_at: string, };
