// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompanyContactMethod = { id: string, company_id: string, 
/**
 * 'email' | 'phone' | 'whatsapp' | 'linkedin' | 'instagram' | 'twitter' | 'website'
 */
method_type: string, label: string | null, value: string, is_primary: number, created_at: string, };
