// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContactResearchPass = { id: string, crm_contact_id: string, pass_number: bigint, research_focus: string, focus_prompt: string | null, status: string, summary: string | null, raw_results: string | null, key_findings: string, search_queries: string, confidence_delta: number, agent_used: string | null, tokens_used: bigint | null, error: string | null, created_at: string, completed_at: string | null, };
