// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentActionRequest = { action: string, task_title: string | null, task_description: string | null, crm_contact_id: string | null, };
