// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContactCompanyRole = { id: string, crm_contact_id: string | null, company_id: string, 
/**
 * 'employee' | 'founder' | 'advisor' | 'consultant' | 'board' | 'investor' | 'contact'
 */
role: string, title: string | null, is_primary: number, start_date: string | null, end_date: string | null, notes: string | null, created_at: string, company_name: string | null, company_slug: string | null, };
