// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContactOrgLink = { id: string, crm_contact_id: string | null, organization_id: string, 
/**
 * 'client' | 'vendor' | 'partner' | 'prospect' | 'contact'
 */
context: string, notes: string | null, added_at: string, org_name: string | null, };
