// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContactSource = "manual" | "email" | "social" | "website" | "referral" | "import" | "api" | "zoho_sync" | "gmail_sync";
