// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentQuery = { project_id: string | null, keyword: string | null, source_id: string | null, status: string | null, limit: bigint | null, offset: bigint | null, };
