// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContactNote = { id: string, crm_contact_id: string | null, author_id: string | null, text: string, 
/**
 * open | follow_up | resolved | pinned
 */
status: string, 
/**
 * JSON: [{name, url, mime_type, size_bytes}]
 */
attachments: string, proposal_id: string | null, created_at: string, updated_at: string, };
