// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CostEstimate = { model: string, provider: string, input_tokens: bigint, output_tokens: bigint, 
/**
 * Cost in cents
 */
cost_cents: bigint, 
/**
 * Cost in VIBE tokens
 */
cost_vibe: bigint, 
/**
 * Cost in USD
 */
cost_usd: number, };
