// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type CreateEmailMessage = { email_account_id: string, project_id: string, provider_message_id: string, thread_id: string | null, from_address: string, from_name: string | null, to_addresses: Array<string>, cc_addresses: Array<string> | null, bcc_addresses: Array<string> | null, reply_to: string | null, subject: string | null, body_text: string | null, body_html: string | null, snippet: string | null, has_attachments: boolean, attachments: JsonValue | null, labels: Array<string> | null, is_read: boolean, is_starred: boolean, is_draft: boolean, is_sent: boolean, received_at: string, sent_at: string | null, };
