// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateCloudFile = { organization_id: string, project_id: string | null, task_id: string | null, file_name: string, file_path: string, storage_volume: string, content_hash: string | null, file_size_bytes: bigint, mime_type: string | null, source_type: string | null, source_id: string | null, source_table: string | null, visibility: string | null, contributed_by: string | null, contributor_wallet: string | null, contributor_device: string | null, };
