// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateDataSource = { organization_id: string | null, project_id: string | null, created_by: string | null, title: string, description: string | null, data_type: string, 
/**
 * "file", "text", or "integration"
 */
source_type: string | null, file_type: string | null, 
/**
 * Raw text content (for source_type = "text")
 */
content: string | null, file_name: string | null, file_path: string | null, file_size_bytes: bigint | null, file_hash: string | null, metadata: string | null, folder: string | null, };
