// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VibeSourceType } from "./VibeSourceType";
import type { JsonValue } from "./serde_json/JsonValue";

export type CreateVibeTransaction = { source_type: VibeSourceType, source_id: string, amount_vibe: bigint, input_tokens: bigint | null, output_tokens: bigint | null, model: string | null, provider: string | null, calculated_cost_cents: bigint | null, task_id: string | null, task_attempt_id: string | null, process_id: string | null, description: string | null, metadata: JsonValue | null, };
