// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateClient = { name: string, slug: string, description: string | null, logo_url: string | null, website: string | null, crm_contact_id: string | null, };
