// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowEventPayload } from "./FlowEventPayload";
import type { FlowEventType } from "./FlowEventType";

export type CreateFlowEvent = { agent_flow_id: string, event_type: FlowEventType, event_data: FlowEventPayload, };
