// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentType } from "./ContentType";
import type { JsonValue } from "./serde_json/JsonValue";

export type CreateSocialPost = { project_id: string, social_account_id: string | null, task_id: string | null, content_type: ContentType | null, caption: string | null, content_blocks: JsonValue | null, media_urls: Array<string> | null, hashtags: Array<string> | null, mentions: Array<string> | null, platforms: Array<string>, platform_specific: JsonValue | null, scheduled_for: string | null, category: string | null, is_evergreen: boolean | null, recycle_after_days: bigint | null, created_by_agent_id: string | null, };
