// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type CreateCrmDeal = { organization_id: string, client_id: string | null, crm_contact_id: string | null, crm_pipeline_id: string | null, crm_stage_id: string | null, name: string, description: string | null, amount: number | null, currency: string | null, expected_close_date: string | null, tags: Array<string> | null, custom_fields: JsonValue | null, };
