// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MentionPriority } from "./MentionPriority";
import type { MentionType } from "./MentionType";
import type { Sentiment } from "./Sentiment";

export type CreateSocialMention = { social_account_id: string, project_id: string, mention_type: MentionType, platform: string, platform_mention_id: string, author_username: string | null, author_display_name: string | null, author_avatar_url: string | null, author_follower_count: bigint | null, author_is_verified: boolean | null, content: string | null, media_urls: Array<string> | null, parent_post_id: string | null, parent_platform_id: string | null, sentiment: Sentiment | null, priority: MentionPriority | null, received_at: string, };
