// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateCrmPipelineStage = { pipeline_id: string, name: string, description: string | null, color: string, position: number, is_closed: boolean | null, is_won: boolean | null, probability: number, };
