// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmsDirection } from "./SmsDirection";
import type { SmsStatus } from "./SmsStatus";

export type CreateSmsMessage = { project_id: string, message_sid: string, account_sid: string | null, messaging_service_sid: string | null, from_number: string, to_number: string, body: string, num_segments: number | null, num_media: number | null, media_urls: Array<string> | null, direction: SmsDirection, status: SmsStatus, date_sent: string | null, };
