// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type CreatePulseSource = { project_id: string, organization_id: string | null, source_id: string, source_type: string, name: string, url: string, config: JsonValue | null, enabled: boolean | null, collection_interval_secs: bigint | null, category: string | null, };
