// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateProjectOnboarding = { project_id: string, context_data: string | null, };
