// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RewardType } from "./RewardType";
import type { JsonValue } from "./serde_json/JsonValue";

export type CreatePeerReward = { peer_node_id: string, contribution_id: string | null, reward_type: RewardType, base_amount: number, multiplier: number, description: string | null, metadata: JsonValue | null, };
