// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type CreateListing = { provider_type: string | null, provider_node_id: string | null, provider_org_id: string | null, provider_wallet: string, service_type: string, service_name: string, service_description: string | null, tags: Array<string> | null, pricing_model: string | null, price_vibe: number, min_vibe: number | null, max_concurrent: bigint | null, endpoint_url: string | null, region: string | null, metadata: JsonValue | null, };
