// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type CreateInvoice = { person_id: string | null, organization_id: string | null, project_id: string | null, 
/**
 * 'ar' | 'ap'
 */
invoice_type: string | null, title: string | null, description: string | null, amount_usd: number | null, amount_vibe: bigint | null, currency: string | null, line_items: Array<JsonValue> | null, issue_date: string | null, due_date: string | null, notes: string | null, created_by: string | null, };
