// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateDeliverable = { project_id: string, proposal_id: string | null, deliverable_type: string | null, title: string, description: string | null, revision_rounds_allowed: bigint | null, working_file_url: string | null, due_date: string | null, };
