// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PipelineType } from "./PipelineType";

export type CreateCrmPipeline = { organization_id: string | null, client_id: string | null, name: string, description: string | null, pipeline_type: PipelineType, icon: string | null, color: string | null, };
