// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrmActivityType } from "./CrmActivityType";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Data for creating a new CRM activity
 */
export type CreateCrmActivity = { organization_id: string | null, client_id: string | null, crm_contact_id: string | null, crm_deal_id: string | null, activity_type: CrmActivityType, subject: string | null, description: string | null, outcome: string | null, email_message_id: string | null, social_mention_id: string | null, task_id: string | null, performed_by_user: string | null, performed_by_agent_id: string | null, metadata: JsonValue | null, duration_minutes: number | null, };
