// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type CreateTokenUsage = { task_attempt_id: string | null, agent_id: string | null, project_id: string, model: string, provider: string | null, input_tokens: bigint, output_tokens: bigint, operation_type: string | null, metadata: JsonValue | null, };
