// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Canvas } from "./Canvas";

export type CreateDeckDocument = { deal_id: string, canvas?: Canvas, brand_token_version?: string, };
