// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateUserRequest = { username: string, email: string, password: string, full_name: string, is_admin: boolean, };
