// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateCompany = { name: string, slug: string | null, website: string | null, industry: string | null, description: string | null, logo_url: string | null, headquarters: string | null, created_by_org_id: string | null, };
