// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateOrganization = { name: string, slug: string, description: string | null, avatar_url: string | null, };
