// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type CreatePulseAlertRule = { project_id: string, organization_id: string | null, name: string, conditions: JsonValue, actions: JsonValue, priority: string | null, enabled: boolean | null, };
