// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateVideoJob = { avatar_profile_id: string, script_text: string, background_url: string | null, segments_json: string | null, };
