// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateVibeWithdrawal = { project_id: string, destination_address: string, amount_vibe: number, };
