// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateMeetingSession = { project_id: string, title: string | null, started_by: string, };
