// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SegmentType } from "./SegmentType";

export type CreateOnboardingSegment = { onboarding_id: string, project_id: string, segment_type: SegmentType, name: string, assigned_agent_id: string | null, assigned_agent_name: string | null, order_index: number, };
