// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QBEnvironment } from "./QBEnvironment";

export type CreateQuickBooksAccount = { organization_id: string, realm_id: string, company_name: string | null, access_token: string | null, refresh_token: string | null, token_expires_at: string | null, environment: QBEnvironment | null, connected_by: string | null, };
