// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrchestrationTaskType } from "./OrchestrationTaskType";

/**
 * Parameters for creating a new orchestration task
 */
export type CreateOrchestrationTask = { agent_flow_id: string, task_type: OrchestrationTaskType, description: string, tool_use_id: string | null, is_concurrency_safe: boolean, position: number, };
