// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResearchTarget } from "./ResearchTarget";

export type CreateWideResearchSession = { agent_flow_id: string | null, parent_agent_id: string | null, task_description: string, targets: Array<ResearchTarget>, parallelism_limit: number | null, timeout_per_subagent: number | null, };
