// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type CreatePerson = { full_name: string, email: string | null, phone: string | null, avatar_url: string | null, person_type: string | null, financial_role: string | null, client_profile: string | null, business_stage: string | null, lifecycle_stage: string | null, lead_score: number | null, company_name: string | null, job_title: string | null, website: string | null, organization_id: string | null, notes: string | null, tags: Array<string> | null, custom_fields: JsonValue | null, onboarding_channel: string | null, preferred_contact: string | null, };
