// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallDirection } from "./CallDirection";
import type { CallStatus } from "./CallStatus";

export type CreateCallLog = { project_id: string, call_sid: string, parent_call_sid: string | null, account_sid: string | null, from_number: string, to_number: string, from_formatted: string | null, to_formatted: string | null, caller_name: string | null, direction: CallDirection, status: CallStatus, answered_by: string | null, start_time: string | null, };
