// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateCloudContribution = { organization_id: string, cloud_file_id: string, user_id: string | null, wallet_address: string | null, device_id: string | null, contribution_type: string | null, channel: string | null, project_id: string | null, task_id: string | null, description: string | null, metadata: string | null, };
