// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatePeerNode = { node_id: string, peer_id: string | null, wallet_address: string, capabilities: Array<string> | null, cpu_cores: bigint | null, ram_mb: bigint | null, storage_gb: bigint | null, gpu_available: boolean, gpu_model: string | null, };
