// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewType } from "./ReviewType";
import type { JsonValue } from "./serde_json/JsonValue";

export type CreateArtifactReview = { artifact_id: string, reviewer_id: string | null, reviewer_agent_id: string | null, reviewer_name: string | null, review_type: ReviewType, feedback_text: string | null, rating: number | null, revision_notes: JsonValue | null, revision_deadline: string | null, };
