// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateScheduledMeetingInvitee } from "./CreateScheduledMeetingInvitee";

export type CreateScheduledMeeting = { proposal_id: string, scheduled_at: string, duration_min: number | null, location: string | null, agenda: string | null, channel: string, invitees: Array<CreateScheduledMeetingInvitee>, };
