// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateSubscription = { consumer_name: string, consumer_type: string | null, consumer_project_id: string | null, consumer_org_id: string | null, contact_email: string | null, service_type: string, listing_id: string | null, vibe_budget: number | null, auto_refill_threshold: number | null, auto_refill_amount: number | null, expires_at: string | null, };
