// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fill } from "./Fill";
import type { SlideElement } from "./SlideElement";

export type CreateDeckSlide = { deck_id: string, slide_index: bigint, name?: string, layout_hint?: string, background: Fill, elements: Array<SlideElement>, notes?: string, origin?: string, };
