// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateBoardShare = { board_id: string, target_organization_id: string, permission: string | null, share_type: string | null, };
