// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateWorkflowTrigger = { workflow_id: string, name: string, trigger_type: string | null, filter_data_source_types: Array<string> | null, filter_organization_id: string | null, filter_project_id: string | null, filter_tags: Array<string> | null, model_override: string | null, auto_approve: boolean | null, };
