// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountType } from "./AccountType";
import type { SocialPlatform } from "./SocialPlatform";
import type { JsonValue } from "./serde_json/JsonValue";

export type CreateSocialAccount = { project_id: string, platform: SocialPlatform, account_type: AccountType | null, platform_account_id: string, username: string | null, display_name: string | null, profile_url: string | null, avatar_url: string | null, access_token: string | null, refresh_token: string | null, token_expires_at: string | null, metadata: JsonValue | null, };
