// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CRM Activity record for tracking contact interactions
 */
export type CrmActivity = { id: string, project_id: string, crm_contact_id: string | null, crm_deal_id: string | null, activity_type: string, subject: string | null, description: string | null, outcome: string | null, email_message_id: string | null, social_mention_id: string | null, task_id: string | null, performed_by_user: string | null, performed_by_agent_id: string | null, metadata: string | null, duration_minutes: number | null, activity_at: string, created_at: string, };
