// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Activity types for CRM tracking
 */
export type CrmActivityType = "email_sent" | "email_received" | "email_opened" | "email_clicked" | "call_made" | "call_received" | "call_scheduled" | "meeting_scheduled" | "meeting_completed" | "meeting_cancelled" | "note_added" | "task_created" | "task_completed" | "deal_stage_changed" | "deal_created" | "deal_won" | "deal_lost" | "social_mention" | "social_dm" | "social_comment" | "form_submitted" | "page_visited" | "document_viewed" | "custom";
