// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CrmDeal = { id: string, project_id: string | null, organization_id: string | null, client_id: string | null, crm_contact_id: string | null, crm_pipeline_id: string | null, crm_stage_id: string | null, position: number | null, name: string, description: string | null, amount: number | null, currency: string, pipeline: string, stage: string, probability: number, expected_close_date: string | null, actual_close_date: string | null, last_activity_at: string | null, owner_user_id: string | null, assigned_agent_id: string | null, zoho_deal_id: string | null, external_ids: string | null, tags: string | null, custom_fields: string | null, lost_reason: string | null, win_reason: string | null, proposal_text: string | null, proposal_status: string, deck_url: string | null, 
/**
 * FK to `deck_documents.id` — the structured deck authored by Lux in the
 * creator studio. Coexists with `deck_url` during the Phase 1 cutover;
 * when both are set, the structured document is authoritative.
 */
deck_document_id: string | null, invoice_id: string | null, won_at: string | null, lost_at: string | null, expedited: number, created_at: string, updated_at: string, };
