// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deal with associated contact info for Kanban display
 */
export type CrmDealWithContact = { contact_name: string | null, contact_email: string | null, contact_company: string | null, contact_avatar_url: string | null, project_name: string | null, task_total: bigint, task_done: bigint, deliverable_count: bigint, 
/**
 * person_id from crm_contacts — bridges to persons table for wiki/intel
 */
person_id: string | null, 
/**
 * report_id — id of the business report (wiki) for this deal's person
 */
report_id: string | null, intelligence_status: string | null, intelligence_summary: string | null, intelligence_confidence: number | null, research_pass_count: bigint | null, report_status: string | null, report_review_status: string | null, review_task_id: string | null, review_task_status: string | null, review_task_assignee: string | null, company_intelligence_status: string | null, company_intelligence_summary: string | null, company_id: string | null, active_agent_flow_id: string | null, active_agent_flow_status: string | null, active_agent_name: string | null, active_agent_cancel_deadline: string | null, id: string, project_id: string | null, organization_id: string | null, client_id: string | null, crm_contact_id: string | null, crm_pipeline_id: string | null, crm_stage_id: string | null, position: number | null, name: string, description: string | null, amount: number | null, currency: string, pipeline: string, stage: string, probability: number, expected_close_date: string | null, actual_close_date: string | null, last_activity_at: string | null, owner_user_id: string | null, assigned_agent_id: string | null, zoho_deal_id: string | null, external_ids: string | null, tags: string | null, custom_fields: string | null, lost_reason: string | null, win_reason: string | null, proposal_text: string | null, proposal_status: string, deck_url: string | null, 
/**
 * FK to `deck_documents.id` — the structured deck authored by Lux in the
 * creator studio. Coexists with `deck_url` during the Phase 1 cutover;
 * when both are set, the structured document is authoritative.
 */
deck_document_id: string | null, invoice_id: string | null, won_at: string | null, lost_at: string | null, expedited: number, created_at: string, updated_at: string, };
report_id: string | null, intelligence_status: string | null, intelligence_summary: string | null, intelligence_confidence: number | null, research_pass_count: bigint | null, report_status: string | null, report_review_status: string | null, review_task_id: string | null, review_task_status: string | null, review_task_assignee: string | null, company_intelligence_status: string | null, company_intelligence_summary: string | null, company_id: string | null, active_agent_flow_id: string | null, active_agent_flow_status: string | null, active_agent_name: string | null, active_agent_cancel_deadline: string | null, id: string, project_id: string | null, organization_id: string | null, client_id: string | null, crm_contact_id: string | null, crm_pipeline_id: string | null, crm_stage_id: string | null, position: number | null, name: string, description: string | null, amount: number | null, currency: string, pipeline: string, stage: string, probability: number, expected_close_date: string | null, actual_close_date: string | null, last_activity_at: string | null, owner_user_id: string | null, assigned_agent_id: string | null, zoho_deal_id: string | null, external_ids: string | null, tags: string | null, custom_fields: string | null, lost_reason: string | null, win_reason: string | null, proposal_text: string | null, proposal_status: string, deck_url: string | null, invoice_id: string | null, won_at: string | null, lost_at: string | null, expedited: number, created_at: string, updated_at: string, };
