// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CrmPipelineStage = { id: string, pipeline_id: string, name: string, description: string | null, color: string, position: number, is_closed: number | null, is_won: number | null, probability: number, auto_move_after_days: number | null, notify_on_enter: number | null, stage_type: string | null, 
/**
 * JSON-serialized StageConfig for data-driven pipeline behavior
 */
stage_config: string | null, created_at: string, updated_at: string, };
