// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CrmPipeline = { id: string, project_id: string, name: string, description: string | null, pipeline_type: string, is_active: number | null, is_default: number | null, icon: string | null, color: string | null, created_at: string, updated_at: string, };
