// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DailyTokenUsage = { usage_date: string, project_id: string, model: string, provider: string, total_input_tokens: bigint, total_output_tokens: bigint, total_tokens: bigint, total_cost_cents: bigint | null, request_count: bigint, };
