// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DataSource = { id: string, organization_id: string | null, project_id: string | null, created_by: string | null, title: string, description: string | null, data_type: string, 
/**
 * How data enters the system: "file", "text", or "integration"
 */
source_type: string, file_type: string | null, 
/**
 * Raw text content (for source_type = "text")
 */
content: string | null, file_name: string | null, file_path: string | null, file_size_bytes: bigint | null, file_hash: string | null, 
/**
 * JSON blob — schema varies by data_type + file_type
 */
metadata: string, status: string, processing_error: string | null, 
/**
 * Slash-delimited folder path, e.g. "Meetings/Google Meet"
 */
folder: string, created_at: string, updated_at: string, archived_at: string | null, };
