// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DealTranscript = { id: string, deal_id: string, intake_item_id: string | null, call_log_id: string | null, transcript_text: string | null, summary: string | null, matched_at: string, matched_by: string | null, created_at: string, };
