// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of converting a deal to a project
 */
export type DealConversionResult = { project_id: string, project_name: string, boards_created: number, tasks_created: number, dependencies_created: number, template_used: string, };
