// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Join table: links data sources from the data library to deals.
 * Allows multiple sources per deal. Used by Astra Pass 2 for enriched context.
 */
export type DealDataSource = { id: string, deal_id: string, data_source_id: string, 
/**
 * JSON array of stage names, e.g. ["discovery", "proposal"]. NULL = all stages.
 */
relevant_stages: string | null, 
/**
 * JSON array of agent names, e.g. ["astra", "cash"]. NULL = all agents.
 */
relevant_agents: string | null, linked_by: string | null, created_at: string, };
