// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Slide row. `elements_json` is a serialized `Vec<SlideElement>`.
 */
export type DeckSlide = { id: string, deck_id: string, slide_index: bigint, name: string | null, layout_hint: string | null, 
/**
 * Opaque serialized `Fill`.
 */
background_json: string, 
/**
 * Opaque serialized `Vec<SlideElement>`.
 */
elements_json: string, notes: string | null, 
/**
 * `lux` | `operator`.
 */
origin: string, locked: bigint, created_at: string, updated_at: string, };
