// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lux-authored proposal awaiting operator accept/reject.
 */
export type DeckSuggestion = { id: string, deck_id: string, target_slide_id: string | null, target_element_id: string | null, op: string, payload_json: string, rationale: string | null, status: string, run_id: string | null, created_at: string, resolved_at: string | null, resolved_by: string | null, };
