// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Top-level deck document row. Slides live in a separate table.
 */
export type DeckDocument = { id: string, deal_id: string, version: bigint, brand_token_version: string | null, 
/**
 * Opaque serialized `Canvas`. Use [`DeckDocument::canvas`] to parse.
 */
canvas_json: string, 
/**
 * Who last touched the deck: `lux` | `operator` | `system`.
 */
last_edited_by: string, created_at: string, updated_at: string, };
