// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Canvas } from "./Canvas";
import type { SlideSnapshot } from "./SlideSnapshot";

/**
 * Full deck assembled from `DeckDocument` + its ordered `DeckSlide` rows,
 * with elements and canvas parsed into their typed forms. This is the shape
 * the frontend and renderer consume.
 */
export type DeckSnapshot = { id: string, deal_id: string, version: bigint, brand_token_version?: string, canvas: Canvas, slides: Array<SlideSnapshot>, last_edited_by: string, created_at: string, updated_at: string, };
