// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Immutable deck snapshot at a point in time.
 */
export type DeckRevision = { id: string, deck_id: string, version: bigint, 
/**
 * `lux` | `operator` | user UUID string.
 */
author: string, 
/**
 * Full serialized `DeckSnapshot` for restore/diff.
 */
snapshot_json: string, diff_summary: string | null, created_at: string, };
