// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deliverable for a project — tracks creative/code output through review stages.
 */
export type Deliverable = { id: string, project_id: string, proposal_id: string | null, 
/**
 * video | audio | graphic | copy | code | document | other
 */
deliverable_type: string, title: string, description: string, 
/**
 * working | internal_review | client_review | revision | client_revision | done
 */
status: string, revision_rounds_allowed: bigint, revision_rounds_used: bigint, working_file_url: string | null, final_link: string | null, due_date: string | null, delivered_at: string | null, created_at: string, updated_at: string, };
