// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountStats } from "./AccountStats";

export type EmailInboxStats = { total: bigint, unread: bigint, starred: bigint, needs_response: bigint, by_account: Array<AccountStats>, };
