// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutionProcessLogs = { execution_id: string, logs: string, byte_size: number, inserted_at: Date, };
