// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { GradientStop } from "./GradientStop";

/**
 * Fill variants for backgrounds and shape fills.
 */
export type Fill = { "kind": "solid", color: Color, } | { "kind": "linear-gradient", stops: Array<GradientStop>, angle: number, } | { "kind": "none" };
