// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlowEventType = "phase_started" | "phase_completed" | "artifact_created" | "artifact_updated" | "approval_requested" | "approval_decision" | "wide_research_started" | "subagent_progress" | "wide_research_completed" | "agent_handoff" | "flow_paused" | "flow_resumed" | "flow_failed" | "flow_completed";
