// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GatewayRequest = { id: string, subscription_id: string, listing_id: string | null, service_type: string, provider_node_id: string | null, provider_wallet: string | null, request_method: string | null, request_path: string | null, request_size_bytes: bigint, response_size_bytes: bigint, status: string, error_message: string | null, vibe_charged: number, vibe_rewarded: number, response_ms: bigint | null, created_at: Date, fulfilled_at: Date | null, };
