// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GatewayStats = { total_requests: bigint, fulfilled_requests: bigint, failed_requests: bigint, total_vibe_charged: number, total_vibe_rewarded: number, avg_response_ms: number | null, active_providers: bigint, };
