// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BBox } from "./BBox";
import type { SlideElement } from "./SlideElement";

export type GroupElement = { id: string, bbox: BBox, z: bigint, origin: string, locked_by?: string, opacity?: number, token_refs?: { [key in string]?: string }, children: Array<SlideElement>, };
