// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BBox } from "./BBox";

export type ImageElement = { id: string, bbox: BBox, z: bigint, origin: string, locked_by?: string, opacity?: number, token_refs?: { [key in string]?: string }, 
/**
 * FK to `media_assets.id`. Nullable while the asset is pending a Maci
 * generation (see Phase 7).
 */
asset_id?: string, 
/**
 * `pending` | `resolved` | `failed`.
 */
asset_status: string, asset_request_id?: string, 
/**
 * `cover` | `contain` | `fill`.
 */
fit: string, crop?: BBox, };
