// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IntegrationConnection = { id: string, organization_id: string, project_id?: string, provider: string, provider_account_id: string, display_name?: string, avatar_url?: string, token_expires_at?: Date | null, scopes?: string, status: string, last_sync_at?: Date | null, last_error?: string, metadata: string, created_at: Date, updated_at: Date, };
