// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An Invoice represents either:
 * - AR (Accounts Receivable): a client owes PCG money for services delivered
 * - AP (Accounts Payable):    PCG owes a contractor money for work performed
 */
export type Invoice = { id: string, invoice_number: string, person_id: string | null, organization_id: string | null, project_id: string | null, 
/**
 * 'ar' | 'ap'
 */
invoice_type: string, 
/**
 * 'draft' | 'sent' | 'viewed' | 'paid' | 'partial' | 'overdue' | 'void' | 'cancelled'
 */
status: string, amount_usd: number, amount_vibe: bigint, currency: string, title: string | null, description: string | null, 
/**
 * JSON array of line items
 */
line_items: string, issue_date: string | null, due_date: string | null, paid_at: string | null, payment_method: string | null, payment_reference: string | null, notes: string | null, metadata: string, created_by: string | null, created_at: string, updated_at: string, };
