// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrmDealWithContact } from "./CrmDealWithContact";
import type { CrmPipelineStage } from "./CrmPipelineStage";

export type KanbanStageWithDeals = { stage: CrmPipelineStage, deals: Array<CrmDealWithContact>, total_amount: number, };
