// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KanbanStageWithDeals } from "./KanbanStageWithDeals";

/**
 * Kanban board data structure - deals grouped by stage
 */
export type KanbanBoardData = { pipeline_id: string, pipeline_name: string, stages: Array<KanbanStageWithDeals>, };
