// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LinkTranscriptRequest = { intake_item_id: string | null, call_log_id: string | null, transcript_text: string | null, summary: string | null, matched_by: string | null, };
