// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LinkDataSourceRequest = { data_source_id: string, 
/**
 * Stage names this source is relevant for. Omit for all stages.
 */
relevant_stages: Array<string> | null, 
/**
 * Agent names this source is relevant for. Omit for all agents.
 */
relevant_agents: Array<string> | null, };
