// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactRole } from "./ArtifactRole";

export type LinkArtifactToTask = { task_id: string, artifact_id: string, artifact_role: ArtifactRole | null, display_order: number | null, pinned: boolean | null, added_by: string | null, };
