// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MeetingSession = { id: string, project_id: string, title: string, status: string, started_by: string, started_at: string, ended_at: string | null, duration_seconds: number | null, participant_count: number | null, participants: string | null, transcript: string | null, notes: string | null, metadata: string | null, topology_node_id: string | null, access_level: string | null, shared_with: string | null, created_at: string, updated_at: string, };
