// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MeetingSegment = { id: string, meeting_session_id: string, segment_index: number, speaker_label: string | null, text: string, confidence: number | null, start_time_ms: bigint, end_time_ms: bigint, is_topsi_addressed: boolean, metadata: string | null, created_at: string, };
