// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelPricing = { id: string, model: string, provider: string, 
/**
 * Cost in cents per 1 million input tokens (already includes multiplier)
 */
input_cost_per_million: bigint, 
/**
 * Cost in cents per 1 million output tokens (already includes multiplier)
 */
output_cost_per_million: bigint, 
/**
 * Multiplier applied to market rate (e.g., 2.0 = 2x)
 */
multiplier: number, effective_from: string, created_at: string, };
