// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelCostRow = { model: string, provider: string, total_vibe: number, total_cost_cents: number, transaction_count: number, input_tokens: number, output_tokens: number, };
