// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelCostRow = { model: string, provider: string, total_vibe: bigint, total_cost_cents: bigint, transaction_count: bigint, input_tokens: bigint, output_tokens: bigint, };
