// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Notification = { id: string, user_id: string, organization_id: string | null, title: string, message: string, notification_type: string, source: string | null, source_id: string | null, read_at: string | null, created_at: string, };
