// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Private rate for an operator within an organization.
 * Only visible to admin and project managers.
 */
export type OperatorRate = { id: string, organization_id: string, operator_id: string, 
/**
 * hourly | daily | weekly | monthly | project
 */
duration: string, rate_vibe: bigint, rate_usd: number, notes: string | null, created_at: string, updated_at: string, };
