// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrchestrationTaskStatus } from "./OrchestrationTaskStatus";
import type { OrchestrationTaskType } from "./OrchestrationTaskType";

/**
 * An orchestration task within an agent flow.
 * Multiple tasks can run concurrently based on their is_concurrency_safe flag.
 */
export type OrchestrationTask = { id: string, agent_flow_id: string, task_type: OrchestrationTaskType, status: OrchestrationTaskStatus, description: string, 
/**
 * The tool_use_id that spawned this task (for traceability)
 */
tool_use_id: string | null, 
/**
 * When the task started executing (epoch ms)
 */
start_time_ms: bigint | null, 
/**
 * When the task finished (epoch ms)
 */
end_time_ms: bigint | null, 
/**
 * Task output on success
 */
output: string | null, 
/**
 * Error message on failure
 */
error: string | null, 
/**
 * Execution order within the flow
 */
position: number, 
/**
 * Whether this task can run concurrently with others
 */
is_concurrency_safe: boolean, created_at: string, updated_at: string, };
