// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextEntryStatus } from "./ContextEntryStatus";
import type { ContextEntryType } from "./ContextEntryType";
import type { ContextPriority } from "./ContextPriority";

export type OrchestrationContext = { id: string, root_task_id: string, project_id: string, task_id: string | null, entry_type: ContextEntryType, title: string, content: string, source: string, status: ContextEntryStatus, priority: ContextPriority, resolved_by: string | null, resolved_at: string | null, metadata: string | null, created_at: string, updated_at: string, };
