// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrgMemberUser } from "./OrgMemberUser";

export type OrganizationMember = { id: string, organization_id: string, user_id: string, role: string, joined_at: string, user: OrgMemberUser | null, };
