// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type Organization = { id: string, name: string, slug: string, description: string | null, avatar_url: string | null, owner_id: string, settings: JsonValue, is_active: boolean, created_at: string, updated_at: string, };
