// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrgCloudSettings = { organization_id: string, storage_quota_bytes: bigint, viewer_can_download: boolean, member_can_upload: boolean, auto_index_data_sources: boolean, auto_index_artifacts: boolean, auto_index_media: boolean, nats_contribution_enabled: boolean, updated_at: string, };
