// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrgCostSummary = { total_vibe: number, total_cost_cents: number, transaction_count: number, total_input_tokens: number, total_output_tokens: number, };
