// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrgCostSummary = { total_vibe: bigint, total_cost_cents: bigint, transaction_count: bigint, total_input_tokens: bigint, total_output_tokens: bigint, };
