// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrgMemberUser = { username: string, full_name: string | null, email: string | null, avatar_url: string | null, };
