// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrgMemberVibeLimit = { organization_id: string, 
/**
 * User id stored as BLOB (legacy `users.id` column).
 */
user_id: string, 
/**
 * NULL = uncapped within the org.
 */
monthly_limit_vibe: bigint | null, current_period_spent: bigint, period_start: string, created_at: Date, updated_at: Date, };
