// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OssLibrary = { id: string, name: string, github_owner: string, github_repo: string, tracked_version: string | null, latest_version: string | null, last_checked_at: string | null, check_interval_secs: bigint, is_active: boolean, notes: string | null, created_at: string, updated_at: string, };
