// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OssLibraryUpdate = { id: string, library_id: string, version: string, release_url: string | null, release_notes: string | null, significance: string, agent_recommendation: string | null, recommendation_status: string, agent_flow_id: string | null, published_at: string | null, created_at: string, };
