// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatchPersonCompanyRole = { role: string | null, title: string | null, is_primary: boolean | null, };
