// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PcgRouterModel = { id: string, name: string, model_id: string, provider: string, provider_base_url: string | null, api_key_env_var: string | null, api_key_value: string | null, priority: bigint, context_window: bigint | null, max_output_tokens: bigint | null, supports_tools: boolean, supports_vision: boolean, cost_per_million_input: bigint, cost_per_million_output: bigint, is_enabled: boolean, created_at: string, updated_at: string, };
