// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeerNode = { id: string, node_id: string, peer_id: string | null, wallet_address: string, capabilities: string | null, cpu_cores: bigint | null, ram_mb: bigint | null, storage_gb: bigint | null, gpu_available: boolean, gpu_model: string | null, first_seen_at: Date, last_heartbeat_at: Date | null, is_active: boolean, is_banned: boolean, ban_reason: string | null, created_at: Date, updated_at: Date, };
