// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeerRewardSummary = { peer_node_id: string, node_id: string, wallet_address: string, pending_vibe: number, distributed_vibe: number, confirmed_vibe: number, total_earned: number, reward_count: bigint, };
