// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeerReward = { id: string, peer_node_id: string, contribution_id: string | null, reward_type: string, base_amount: number, multiplier: number, final_amount: number, status: string, batch_id: string | null, aptos_tx_hash: string | null, block_height: bigint | null, error_message: string | null, retry_count: bigint, description: string | null, metadata: string | null, created_at: Date, updated_at: Date, distributed_at: Date | null, confirmed_at: Date | null, };
