// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Universal Person entity — the single canonical identity record.
 *
 * All PCG users, CRM contacts, leads, contractors, and partners are
 * represented here.  Existing `users` and `crm_contacts` rows are bridged
 * via `user_id` / `crm_contact_id` foreign keys.
 */
export type Person = { id: string, full_name: string, email: string | null, phone: string | null, avatar_url: string | null, 
/**
 * 'team' | 'client' | 'contractor' | 'lead' | 'partner' | 'contact'
 */
person_type: string, 
/**
 * 'taker' | 'giver' | 'both' | 'neutral'
 */
financial_role: string, 
/**
 * 'startup' | 'retainer' | null
 */
client_profile: string | null, 
/**
 * 'idea' | 'funding' | 'manufacturing' | 'distribution' | 'customer_acquisition'
 */
business_stage: string | null, lifecycle_stage: string, lead_score: number, company_name: string | null, job_title: string | null, website: string | null, user_id: string | null, crm_contact_id: string | null, organization_id: string | null, intelligence_summary: string | null, intelligence_raw: string | null, intelligence_last_run_at: string | null, intelligence_confidence: number, notes: string | null, tags: string, custom_fields: string, 
/**
 * How this person first engaged with PCG.
 * 'email'|'instagram'|'whatsapp'|'linkedin'|'twitter'|'sms'|'phone'|'in_person'
 */
onboarding_channel: string | null, 
/**
 * Preferred channel for outbound communication (may differ from onboarding).
 */
preferred_contact: string | null, created_at: string, updated_at: string, };
