// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonSocialProfile } from "./PersonSocialProfile";

/**
 * Rich view that joins social profiles alongside the person.
 */
export type PersonWithSocials = { social_profiles: Array<PersonSocialProfile>, id: string, full_name: string, email: string | null, phone: string | null, avatar_url: string | null, 
/**
 * 'team' | 'client' | 'contractor' | 'lead' | 'partner' | 'contact'
 */
person_type: string, 
/**
 * 'taker' | 'giver' | 'both' | 'neutral'
 */
financial_role: string, 
/**
 * 'startup' | 'retainer' | null
 */
client_profile: string | null, 
/**
 * 'idea' | 'funding' | 'manufacturing' | 'distribution' | 'customer_acquisition'
 */
business_stage: string | null, lifecycle_stage: string, lead_score: number, company_name: string | null, job_title: string | null, website: string | null, user_id: string | null, crm_contact_id: string | null, organization_id: string | null, intelligence_summary: string | null, intelligence_raw: string | null, intelligence_last_run_at: string | null, intelligence_confidence: number, notes: string | null, tags: string, custom_fields: string, created_at: string, updated_at: string, };
