// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PersonSocialProfile = { id: string, person_id: string, 
/**
 * 'linkedin' | 'twitter' | 'instagram' | 'youtube' | 'tiktok' | 'github' | 'facebook' | 'website'
 */
platform: string, handle: string | null, profile_url: string | null, follower_count: bigint | null, following_count: bigint | null, bio: string | null, verified: number, raw_data: string | null, last_synced_at: string | null, created_at: string, updated_at: string, };
