// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectFolder = { id: string, organization_id: string, client_id: string | null, name: string, sort_order: number, is_active: boolean, created_at: Date, updated_at: Date, };
