// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Board types for project boards
 */
export type ProjectBoardType = "default" | "custom" | "brand_assets" | "executive_assets";
