// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectBoardType = "executive_assets" | "brand_assets" | "dev_assets" | "social_assets" | "custom" | "agent_flows" | "artifact_gallery" | "approval_queue" | "research_hub";
