// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Simplified board types - just Default (auto-created) and Custom (user-created)
 */
export type ProjectBoardType = "default" | "custom";
