// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectCostRow = { project_id: string | null, project_name: string, total_vibe: bigint, total_cost_cents: bigint, transaction_count: bigint, };
