// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-project knowledge completeness (from the SQL view)
 */
export type ProjectKnowledgeCompleteness = { project_id: string, total_sources: bigint, fresh_sources: bigint, avg_coverage: number, type_count: bigint, knowledge_completeness: number, };
