// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 8-stage proposal pipeline.
 */
export type Proposal = { id: string, lead_id: string | null, organization_id: string | null, owner_id: string | null, project_id: string | null, 
/**
 * drafted | pending_approval | approved | meeting_scheduled | sent | seen | verbal | contract_signed | declined | deferred
 */
status: string, title: string, description: string, quote_amount_vibe: bigint, 
/**
 * one-off | retainer | hybrid
 */
deal_type: string, sent_at: string | null, seen_at: string | null, verbal_at: string | null, signed_at: string | null, declined_at: string | null, created_at: string, updated_at: string, };
