// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PulseCollectionRun = { id: string, project_id: string, organization_id: string | null, source_id: string, started_at: string, completed_at: string | null, items_collected: bigint, items_new: bigint, items_duplicate: bigint, status: string, error: string | null, vibe_cost: number | null, created_at: string, };
