// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PulseSource = { id: string, project_id: string, organization_id: string | null, source_id: string, source_type: string, name: string, url: string, config: string | null, enabled: boolean, status: string, last_fetch_at: string | null, last_error: string | null, collection_interval_secs: bigint, category: string | null, created_at: string, updated_at: string, };
