// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PulseTrackingConfig = { id: string, project_id: string, organization_id: string | null, keywords: string, entities: string, llm_enabled: boolean, llm_model: string | null, notification_config: string | null, created_at: string, updated_at: string, };
