// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PulseAlertRule = { id: string, project_id: string, organization_id: string | null, name: string, conditions: string, actions: string, priority: string, enabled: boolean, trigger_count: bigint, last_triggered_at: string | null, created_at: string, updated_at: string, };
