// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PulseAlert = { id: string, project_id: string, organization_id: string | null, rule_id: string, content_item_id: string, priority: string, acknowledged: boolean, auto_task_id: string | null, created_at: string, };
