// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sync scope configuration for display
 */
export type QBSyncScope = { invoices: boolean, customers: boolean, payments: boolean, expenses: boolean, time_tracking: boolean, };
