// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mapping between PCG entities and QuickBooks Online entities
 */
export type QuickBooksEntityMap = { id: string, quickbooks_account_id: string, pcg_entity_type: string, pcg_entity_id: string, qbo_entity_type: string, qbo_entity_id: string, qbo_sync_token: string | null, last_synced_at: string | null, sync_direction: string, sync_status: string, last_error: string | null, created_at: string, updated_at: string, };
