// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResearchSessionStatus = "spawning" | "in_progress" | "aggregating" | "completed" | "failed" | "cancelled";
