// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewStatus } from "./ReviewStatus";

export type ResolveReview = { status: ReviewStatus, feedback_text: string | null, rating: number | null, resolved_by: string, };
