// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewType = "approval" | "feedback" | "revision_request" | "quality_check" | "compliance_check";
