// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScheduledMeeting = { id: string, proposal_id: string, scheduled_at: string, duration_min: number, location: string | null, agenda: string | null, channel: string, invite_status: string, invite_sent_at: string | null, notes: string | null, created_at: string, updated_at: string, };
