// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScheduledMeetingInvitee = { id: string, scheduled_meeting_id: string, person_id: string, channel: string, channel_address: string, status: string, sent_at: string | null, created_at: string, };
