// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Session = { id: string, user_id: string, created_at: string, expires_at: string, last_accessed: string, };
