// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BBox } from "./BBox";
import type { Fill } from "./Fill";
import type { Stroke } from "./Stroke";

export type ShapeElement = { id: string, bbox: BBox, z: bigint, origin: string, locked_by?: string, opacity?: number, token_refs?: { [key in string]?: string }, 
/**
 * `rect` | `ellipse` | `line` | `path`.
 */
shape: string, path?: string, fill: Fill, stroke?: Stroke, corner_radius?: number, };
