// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupElement } from "./GroupElement";
import type { ImageElement } from "./ImageElement";
import type { ShapeElement } from "./ShapeElement";
import type { TextElement } from "./TextElement";

/**
 * Element discriminated by `type`. Mirrors the frontend TS union.
 */
export type SlideElement = { "type": "text" } & TextElement | { "type": "image" } & ImageElement | { "type": "shape" } & ShapeElement | { "type": "group" } & GroupElement;
