// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SmsDirection = "inbound" | "outbound" | "outbound_api" | "outbound_call" | "outbound_reply";
