// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SmsStatus = "accepted" | "queued" | "sending" | "sent" | "delivered" | "undelivered" | "failed" | "receiving" | "received" | "read";
