// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SmsStats = { total: bigint, inbound: bigint, outbound: bigint, unread: bigint, needs_response: bigint, };
