// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SocialAccount = { id: string, project_id: string, platform: string, account_type: string, platform_account_id: string, username: string | null, display_name: string | null, profile_url: string | null, avatar_url: string | null, token_expires_at: string | null, follower_count: bigint | null, following_count: bigint | null, post_count: bigint | null, metadata: string | null, status: string, last_sync_at: string | null, last_error: string | null, created_at: string, updated_at: string, 
/**
 * FK into `integration_connections` for OAuth-managed tokens.
 * When set, callers should use `oauth_token_manager::get_access_token`
 * to obtain a fresh, decrypted token rather than reading `access_token`.
 */
integration_connection_id?: string, };
