// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SocialPlatform = "instagram" | "linked_in" | "twitter" | "tik_tok" | "you_tube" | "facebook" | "threads" | "bluesky" | "pinterest";
