// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";

export type Stroke = { color: Color, width: number, 
/**
 * `solid` | `dashed` | `dotted`.
 */
style: string, };
