// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Safe view — omits api_key, shows only prefix
 */
export type SubscriptionView = { id: string, consumer_name: string, consumer_type: string, service_type: string, listing_id: string | null, api_key_prefix: string, vibe_budget: number, vibe_spent: number, vibe_balance: number, status: string, created_at: Date, expires_at: Date | null, };
