// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full response including the API key — only returned on creation
 */
export type SubscriptionCreated = { id: string, consumer_name: string, service_type: string, api_key: string, api_key_prefix: string, vibe_budget: number, status: string, created_at: Date, };
