// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskTemplate = { id: string, project_id: string | null, title: string, description: string | null, template_name: string, priority: string | null, completion_criteria: string | null, output_format: string | null, assigned_agent: string | null, tags: string | null, organization_id: string | null, created_at: string, updated_at: string, };
