// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactRole } from "./ArtifactRole";

export type TaskArtifact = { task_id: string, artifact_id: string, artifact_role: ArtifactRole, display_order: number, pinned: boolean, added_at: string, added_by: string | null, };
