// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BBox } from "./BBox";
import type { Color } from "./Color";
import type { TextRun } from "./TextRun";

/**
 * Fields common to every element variant. Kept flat on each variant so the
 * serde tag discriminator remains clean.
 */
export type TextElement = { id: string, bbox: BBox, z: bigint, 
/**
 * `lux` | `operator`.
 */
origin: string, locked_by?: string, opacity?: number, token_refs?: { [key in string]?: string }, text: string, font_family: string, font_size: number, font_weight: bigint, line_height: number, letter_spacing: number, color: Color, 
/**
 * `left` | `center` | `right` | `justify`.
 */
align: string, runs?: Array<TextRun>, };
