// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenUsage = { id: string, task_attempt_id: string | null, agent_id: string | null, project_id: string, model: string, provider: string, input_tokens: bigint, output_tokens: bigint, total_tokens: bigint, cost_cents: bigint | null, operation_type: string | null, metadata: string | null, created_at: string, };
