// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenUsageByProject = { project_id: string, project_name: string | null, total_tokens: bigint, request_count: bigint, };
