// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenUsageByAgent = { agent_id: string, agent_name: string | null, total_tokens: bigint, request_count: bigint, };
