// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TriggerExecution = { id: string, trigger_id: string, workflow_run_id: string | null, status: string, started_at: string, completed_at: string | null, duration_ms: bigint | null, error: string | null, records_staged: bigint, source_type: string | null, source_id: string | null, metadata: string | null, created_at: string, };
