// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallStatus } from "./CallStatus";

export type UpdateCallLog = { status: CallStatus | null, answered_by: string | null, end_time: string | null, duration_seconds: number | null, recording_url: string | null, recording_sid: string | null, recording_duration: number | null, transcription: string | null, transcription_status: string | null, summary: string | null, sentiment: string | null, crm_contact_id: string | null, price: number | null, };
