// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateProjectFolder = { name: string | null, sort_order: number | null, is_active: boolean | null, };
