// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateProposal = { title: string | null, description: string | null, quote_amount_vibe: bigint | null, deal_type: string | null, lead_id: string | null, project_id: string | null, owner_id: string | null, };
