// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeetingStatus } from "./MeetingStatus";

export type UpdateMeetingSession = { title: string | null, status: MeetingStatus | null, ended_at: string | null, duration_seconds: number | null, participant_count: number | null, participants: string | null, transcript: string | null, notes: string | null, topology_node_id: string | null, shared_with: string | null, };
