// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OnboardingStatus } from "./OnboardingStatus";

export type UpdateProjectOnboarding = { status: OnboardingStatus | null, current_phase: string | null, context_data: string | null, recommendations: string | null, };
