// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateOrganization = { name: string | null, slug: string | null, description: string | null, avatar_url: string | null, address: string | null, };
