// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateUserRequest = { email: string | null, full_name: string | null, is_active: boolean | null, is_admin: boolean | null, };
