// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type UpdateCrmDeal = { crm_contact_id: string | null, crm_pipeline_id: string | null, crm_stage_id: string | null, position: number | null, name: string | null, description: string | null, amount: number | null, currency: string | null, expected_close_date: string | null, owner_user_id: string | null, assigned_agent_id: string | null, tags: Array<string> | null, custom_fields: JsonValue | null, lost_reason: string | null, win_reason: string | null, };
