// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateDeliverable = { title: string | null, description: string | null, deliverable_type: string | null, revision_rounds_allowed: bigint | null, working_file_url: string | null, final_link: string | null, due_date: string | null, };
