// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPhase } from "./AgentPhase";
import type { FlowStatus } from "./FlowStatus";

export type UpdateAgentFlow = { status: FlowStatus | null, current_phase: AgentPhase | null, planner_agent_id: string | null, executor_agent_id: string | null, verifier_agent_id: string | null, handoff_instructions: string | null, verification_score: number | null, approved_by: string | null, };
