// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type UpdatePulseSource = { name: string | null, url: string | null, config: JsonValue | null, enabled: boolean | null, collection_interval_secs: bigint | null, category: string | null, };
