// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type UpdatePulseTrackingConfig = { keywords: JsonValue | null, entities: JsonValue | null, llm_enabled: boolean | null, llm_model: string | null, notification_config: JsonValue | null, };
