// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type UpdateInvoice = { status: string | null, title: string | null, description: string | null, amount_usd: number | null, amount_vibe: bigint | null, due_date: string | null, paid_at: string | null, payment_method: string | null, payment_reference: string | null, line_items: Array<JsonValue> | null, notes: string | null, };
