// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type UpdateListing = { service_name: string | null, service_description: string | null, tags: Array<string> | null, pricing_model: string | null, price_vibe: number | null, min_vibe: number | null, max_concurrent: bigint | null, endpoint_url: string | null, region: string | null, status: string | null, metadata: JsonValue | null, };
