// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateOrgCloudSettings = { storage_quota_bytes: bigint | null, viewer_can_download: boolean | null, member_can_upload: boolean | null, auto_index_data_sources: boolean | null, auto_index_artifacts: boolean | null, auto_index_media: boolean | null, nats_contribution_enabled: boolean | null, };
