// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactSource } from "./ContactSource";
import type { LifecycleStage } from "./LifecycleStage";
import type { JsonValue } from "./serde_json/JsonValue";

export type UpdateCrmContact = { first_name: string | null, last_name: string | null, email: string | null, phone: string | null, mobile: string | null, avatar_url: string | null, company_name: string | null, job_title: string | null, department: string | null, linkedin_url: string | null, twitter_handle: string | null, website: string | null, source: ContactSource | null, lifecycle_stage: LifecycleStage | null, lead_score: number | null, owner_user_id: string | null, assigned_agent_id: string | null, tags: Array<string> | null, custom_fields: JsonValue | null, address_line1: string | null, address_line2: string | null, city: string | null, state: string | null, postal_code: string | null, country: string | null, email_opt_in: boolean | null, sms_opt_in: boolean | null, do_not_contact: boolean | null, zoho_contact_id: string | null, gmail_contact_id: string | null, };
