// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmailPriority } from "./EmailPriority";
import type { EmailSentiment } from "./EmailSentiment";

export type UpdateEmailMessage = { is_read: boolean | null, is_starred: boolean | null, is_archived: boolean | null, is_spam: boolean | null, is_trash: boolean | null, labels: Array<string> | null, crm_contact_id: string | null, crm_deal_id: string | null, sentiment: EmailSentiment | null, priority: EmailPriority | null, needs_response: boolean | null, response_due_at: string | null, responded_at: string | null, };
