// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdatePeerResources = { cpu_cores: bigint | null, ram_mb: bigint | null, storage_gb: bigint | null, gpu_available: boolean, gpu_model: string | null, };
