// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateCrmPipelineStage = { name: string | null, description: string | null, color: string | null, position: number | null, is_closed: boolean | null, is_won: boolean | null, probability: number | null, stage_config: string | null, };
