// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type UpdatePulseAlertRule = { name: string | null, conditions: JsonValue | null, actions: JsonValue | null, priority: string | null, enabled: boolean | null, };
