// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmailAccountStatus } from "./EmailAccountStatus";
import type { JsonValue } from "./serde_json/JsonValue";

export type UpdateEmailAccount = { display_name: string | null, avatar_url: string | null, access_token: string | null, refresh_token: string | null, token_expires_at: string | null, imap_host: string | null, imap_port: number | null, smtp_host: string | null, smtp_port: number | null, use_ssl: boolean | null, granted_scopes: Array<string> | null, storage_used_bytes: bigint | null, storage_total_bytes: bigint | null, unread_count: number | null, metadata: JsonValue | null, status: EmailAccountStatus | null, last_error: string | null, sync_enabled: boolean | null, sync_frequency_minutes: number | null, auto_reply_enabled: boolean | null, signature: string | null, };
