// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SegmentStatus } from "./SegmentStatus";

export type UpdateOnboardingSegment = { status: SegmentStatus | null, recommendations: string | null, user_decisions: string | null, assigned_agent_id: string | null, assigned_agent_name: string | null, };
