// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmsStatus } from "./SmsStatus";

export type UpdateSmsMessage = { status: SmsStatus | null, error_code: string | null, error_message: string | null, auto_response: string | null, sentiment: string | null, crm_contact_id: string | null, is_read: boolean | null, is_starred: boolean | null, needs_response: boolean | null, responded_at: string | null, price: number | null, };
