// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QBAccountStatus } from "./QBAccountStatus";
import type { JsonValue } from "./serde_json/JsonValue";

export type UpdateQuickBooksAccount = { company_name: string | null, sync_enabled: boolean | null, sync_frequency_minutes: number | null, sync_invoices: boolean | null, sync_customers: boolean | null, sync_payments: boolean | null, sync_expenses: boolean | null, sync_time_tracking: boolean | null, status: QBAccountStatus | null, last_error: string | null, metadata: JsonValue | null, };
