// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateCloudFile = { file_name: string | null, visibility: string | null, project_id: string | null, task_id: string | null, };
