// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateCloudStorageAccount = { auto_sync: boolean | null, sync_interval_secs: bigint | null, sync_root_path: string | null, };
