// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateClient = { name: string | null, slug: string | null, description: string | null, logo_url: string | null, website: string | null, crm_contact_id: string | null, is_active: boolean | null, };
