// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostStatus } from "./PostStatus";
import type { JsonValue } from "./serde_json/JsonValue";

export type UpdateSocialPost = { caption: string | null, content_blocks: JsonValue | null, media_urls: Array<string> | null, hashtags: Array<string> | null, mentions: Array<string> | null, platform_specific: JsonValue | null, status: PostStatus | null, scheduled_for: string | null, category: string | null, queue_position: bigint | null, is_evergreen: boolean | null, approved_by: string | null, };
