// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateTaskTemplate = { title: string | null, description: string | null, template_name: string | null, priority: string | null, completion_criteria: string | null, output_format: string | null, assigned_agent: string | null, tags: Array<string> | null, };
