// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MentionPriority } from "./MentionPriority";
import type { MentionStatus } from "./MentionStatus";
import type { Sentiment } from "./Sentiment";

export type UpdateSocialMention = { status: MentionStatus | null, sentiment: Sentiment | null, priority: MentionPriority | null, replied_by: string | null, reply_content: string | null, assigned_agent_id: string | null, };
