// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountStatus } from "./AccountStatus";
import type { JsonValue } from "./serde_json/JsonValue";

export type UpdateSocialAccount = { username: string | null, display_name: string | null, profile_url: string | null, avatar_url: string | null, access_token: string | null, refresh_token: string | null, token_expires_at: string | null, follower_count: number | null, following_count: number | null, post_count: number | null, metadata: JsonValue | null, status: AccountStatus | null, last_error: string | null, };
