// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateDataSource = { title: string | null, description: string | null, data_type: string | null, source_type: string | null, content: string | null, metadata: string | null, status: string | null, processing_error: string | null, folder: string | null, };
