// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpsertOperatorRate = { organization_id: string, operator_id: string, duration: string, rate_vibe: bigint, rate_usd: number | null, notes: string | null, };
