// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create/update brand profile payload
 */
export type UpsertBrandProfile = { tagline: string | null, industry: string | null, primaryColor: string | null, secondaryColor: string | null, brandVoice: string | null, targetAudience: string | null, logoAssetId: string | null, guidelinesAssetId: string | null, };
