// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpsertPersonCompanyRole = { company_id: string, role: string | null, title: string | null, is_primary: boolean | null, start_date: string | null, end_date: string | null, notes: string | null, };
