// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpsertOrgMemberVibeLimit = { organization_id: string, user_id: string, 
/**
 * NULL clears the cap (uncapped within the org).
 */
monthly_limit_vibe: bigint | null, };
