// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrganizationRole } from "./OrganizationRole";

export type UserOrganization = { id: string, name: string, slug: string, role: OrganizationRole, };
