// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type User = { id: string, username: string, email: string, password_hash: string, full_name: string, avatar_url: string | null, is_active: boolean, is_admin: boolean, last_login_at: string | null, created_at: string, updated_at: string, };
