// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserOrganization } from "./UserOrganization";

export type UserProfile = { id: string, username: string, email: string, full_name: string, avatar_url: string | null, is_admin: boolean, organizations: Array<UserOrganization>, };
