// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VibeTransactionSummary = { total_vibe: bigint, total_cost_cents: bigint | null, transaction_count: bigint, };
