// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * VIBE deposit from user wallet to treasury
 */
export type VibeDeposit = { id: string, project_id: string, tx_hash: string, sender_address: string, amount_vibe: number, status: string, block_height: bigint | null, detected_at: Date, credited_at: Date | null, error_message: string | null, created_at: Date, updated_at: Date, };
