// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * VIBE withdrawal request from project balance
 */
export type VibeWithdrawal = { id: string, project_id: string, destination_address: string, amount_vibe: number, status: string, tx_hash: string | null, requested_at: Date, processed_at: Date | null, error_message: string | null, created_at: Date, updated_at: Date, };
