// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VibeTransaction = { id: string, source_type: string, source_id: string, amount_vibe: bigint, input_tokens: bigint | null, output_tokens: bigint | null, model: string | null, provider: string | null, calculated_cost_cents: bigint | null, aptos_tx_hash: string | null, aptos_tx_status: string | null, task_id: string | null, task_attempt_id: string | null, process_id: string | null, description: string | null, metadata: string | null, 
/**
 * Whether this transaction has been synced to the blockchain
 */
on_chain_synced: boolean, created_at: string, updated_at: string, };
