// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResearchSessionStatus } from "./ResearchSessionStatus";

export type WideResearchSession = { id: string, agent_flow_id: string | null, parent_agent_id: string | null, task_description: string, total_subagents: number, completed_subagents: number, failed_subagents: number, status: ResearchSessionStatus, parallelism_limit: number | null, timeout_per_subagent: number | null, aggregated_result_artifact_id: string | null, created_at: string, completed_at: string | null, };
