// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubagentStatus } from "./SubagentStatus";

export type WideResearchSubagent = { id: string, session_id: string, subagent_index: number, target_item: string, target_metadata: string | null, status: SubagentStatus, execution_process_id: string | null, result_artifact_id: string | null, error_message: string | null, started_at: string | null, completed_at: string | null, };
