// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowTaskType } from "./WorkflowTaskType";

/**
 * A task within a workflow phase
 */
export type WorkflowTaskTemplate = { title: string, description: string, position: number, task_type: WorkflowTaskType, 
/**
 * Which agent role handles this task (scout, astra, creative, etc.)
 */
agent_role: string | null, 
/**
 * Whether this task blocks the pipeline until a human approves
 */
requires_approval: boolean, 
/**
 * Priority level
 */
priority: string, 
/**
 * Positions (within the same phase) this task depends on
 */
depends_on: Array<number>, 
/**
 * Knowledge domains this task reads from
 */
knowledge_inputs: Array<string>, 
/**
 * Knowledge domains this task produces/enriches
 */
knowledge_outputs: Array<string>, 
/**
 * Tags for categorization
 */
tags: Array<string>, };
