// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowTrigger = { id: string, workflow_id: string, name: string, enabled: boolean, trigger_type: string, filter_data_source_types: string | null, filter_organization_id: string | null, filter_project_id: string | null, filter_tags: string | null, model_override: string | null, auto_approve: boolean, last_triggered_at: string | null, trigger_count: bigint, created_at: string, updated_at: string, };
