// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task execution type — who does the work
 */
export type WorkflowTaskType = "agent" | "human_review" | "hybrid";
