// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientType } from "./ClientType";
import type { WorkflowPhaseTemplate } from "./WorkflowPhaseTemplate";

/**
 * A complete workflow template
 */
export type WorkflowTemplate = { id: string, name: string, description: string, client_type: ClientType, 
/**
 * Whether the overall engagement is recurring (retainer vs project)
 */
is_recurring: boolean, 
/**
 * Phases of the workflow
 */
phases: Array<WorkflowPhaseTemplate>, };
