// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowTaskTemplate } from "./WorkflowTaskTemplate";

/**
 * A phase within a workflow template (becomes a board when scaffolded)
 */
export type WorkflowPhaseTemplate = { name: string, description: string, position: number, 
/**
 * Whether this phase repeats (for managed growth monthly cycles)
 */
is_recurring: boolean, 
/**
 * Tasks within this phase
 */
tasks: Array<WorkflowTaskTemplate>, };
