// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An action item from a meeting
 */
export type ActionItem = { 
/**
 * Description of the action
 */
description: string, 
/**
 * Person assigned to this action
 */
assignee: string | null, 
/**
 * Deadline for completion
 */
deadline: string | null, 
/**
 * Priority level
 */
priority: string | null, };
