// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionItem } from "./ActionItem";

/**
 * Structured meeting notes generated by LLM
 */
export type MeetingNotes = { 
/**
 * Executive summary of the meeting
 */
summary: string, 
/**
 * Main topics discussed
 */
topics: Array<string>, 
/**
 * Decisions made during the meeting
 */
decisions: Array<string>, 
/**
 * Action items with assignees and deadlines
 */
actionItems: Array<ActionItem>, 
/**
 * Open questions that remain unresolved
 */
openQuestions: Array<string>, 
/**
 * Participants identified in the meeting
 */
participants: Array<string>, };
