// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single transcript entry from the meeting
 */
export type MeetingTranscriptEntry = { 
/**
 * Speaker label (e.g. "Speaker 1", "Alice")
 */
speakerLabel: string | null, 
/**
 * Transcribed text
 */
text: string, 
/**
 * Confidence score from STT
 */
confidence: number, 
/**
 * Start time in milliseconds from meeting start
 */
startTimeMs: bigint, 
/**
 * End time in milliseconds from meeting start
 */
endTimeMs: bigint, 
/**
 * Whether this segment addressed Topsi
 */
isTopsiAddressed: boolean, 
/**
 * Segment index within the meeting
 */
segmentIndex: number, };
