// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a detected speaker
 */
export type SpeakerInfo = { 
/**
 * Speaker label from diarization (e.g. "SPEAKER_00")
 */
label: string, 
/**
 * Optional display name (user-assigned or auto-detected)
 */
displayName: string | null, 
/**
 * Number of segments spoken
 */
segmentCount: number, 
/**
 * Total speaking time in milliseconds
 */
speakingTimeMs: bigint, };
