// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of wake word detection
 */
export type WakeWordResult = { 
/**
 * Whether the wake word was detected
 */
detected: boolean, 
/**
 * Text following the wake word (the addressed command/question)
 */
addressedText: string | null, 
/**
 * Position of the wake word in the original text
 */
position: number | null, };
